// Code generated by go-bindata.
// sources:
// test-certs/binding-cache-ca.crl
// test-certs/binding-cache-ca.crt
// test-certs/binding-cache-ca.key
// test-certs/capi-ca.crl
// test-certs/capi-ca.crt
// test-certs/capi-ca.key
// test-certs/doppler.crt
// test-certs/doppler.csr
// test-certs/doppler.key
// test-certs/expvar-forwarder.crt
// test-certs/expvar-forwarder.csr
// test-certs/expvar-forwarder.key
// test-certs/forwarder.crt
// test-certs/forwarder.csr
// test-certs/forwarder.key
// test-certs/loggregator-ca.crl
// test-certs/loggregator-ca.crt
// test-certs/loggregator-ca.key
// test-certs/metron.crt
// test-certs/metron.csr
// test-certs/metron.key
// test-certs/prom-scraper.crt
// test-certs/prom-scraper.csr
// test-certs/prom-scraper.key
// test-certs/router.crt
// test-certs/router.csr
// test-certs/router.key
// test-certs/syslog-agent.crt
// test-certs/syslog-agent.csr
// test-certs/syslog-agent.key
// test-certs/system-metrics-agent-ca.crl
// test-certs/system-metrics-agent-ca.crt
// test-certs/system-metrics-agent-ca.key
// DO NOT EDIT!

package testhelper

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindingCacheCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICiDByAgEBMA0GCSqGSIb3DQEBCwUAMBkxFzAVBgNVBAMTDmJpbmRpbmdDYWNo
ZUNBFw0xOTAxMTcxODMzMzFaFw00NDAxMTcxODMzMjhaMACgIzAhMB8GA1UdIwQY
MBaAFGq1Jsz+9ltLUARQNR5aah5yYxBFMA0GCSqGSIb3DQEBCwUAA4ICAQBOByKe
g19bc2Ctntpk5P4KbNRS6KV0HeDUm1OcdhtxMvOekqhTczSFt7FddAu2SDFqL8DL
xE2xqq3HAkHrCg7D1HbyVRM1CexJM6ZN38zXGHeFCiT39AJHykuR4TM9HIC7KtI1
VNpq12uIoyqii+bJ/R9aQq/cHwDMgZfGYkPcpt+Gr2TadtVDmtSy6/TeY7rr/rJA
lPFD/6BcDkmBLvos5KbxEhSnswxhvhSYpJhOF+gp67rxc21fUeAcatzHM9u/4zY9
eUCaCyLoySkEzheAQT8HbNnIfKI27PvZQtMFKQZlm6xTx0o0LZgeyvRrU+2wMtmS
qSKAaCDbb/9ZJfMrtIi5HPkHPefQKgZZs9ceHUcyCaKEIfTRT8v+70SFTTxuk7z7
6gj2d3nzb5ym748g38ANIOaqf5ITtbqx3qCLou2OKLjX2KwCvpAXU96kXEpKxZX2
Qky2KwJVfP9j6U0rRaZ5/P92O3E1InMekQPj1oyyaMpCqRd+lQf6S7pJuPuUDdfA
0cjS/i2MvzUBp+bnrL0nPRUwiJczSEizpyIspuvm98JCy+4yhsEq2d07T2saS4wZ
+PoRLN4vsjyNuqhhP9mlwObUTbDMeR1q/hNMwYqmFdzRycuBjgE2DhTBVYf7KvpB
fOf19k6pv4v83NatBskbFNwbAO0Zgi9MMVyRQQ==
-----END X509 CRL-----
`)

func bindingCacheCaCrlBytes() ([]byte, error) {
	return _bindingCacheCaCrl, nil
}

func bindingCacheCaCrl() (*asset, error) {
	bytes, err := bindingCacheCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.crl", size: 934, mode: os.FileMode(292), modTime: time.Unix(1547750011, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindingCacheCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8jCCAtqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5iaW5k
aW5nQ2FjaGVDQTAeFw0xOTAxMTcxODMzMjhaFw00NDAxMTcxODMzMjhaMBkxFzAV
BgNVBAMTDmJpbmRpbmdDYWNoZUNBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAonvtuQ1kvuK8kuOPo3MU05mxfrYVhvaIkTAs5OlQwwgR1SqidfhZS7Dv
n+K0SZGY0H0wa9axBJyEcgLK1ZqQ4YFReuLZMrlGsQ0Rmw7BRDCdyXARntXMepNh
cH38dA++WRw2XgQTlEBidJ3nJ0Qdo8SSbok7guDj1aMVa/zZ4HrqwYvOjOp1vO6I
SwmxMKAAPsDj5A23kYFnXJpnGO8CXB3Aheg1UDhJ6ljzIFLTlIryZ9tdqo2H9+JF
JzCBZj5M24JvhBGICvZckbi9LNaX/SlSpz6XJjq+YodTzDQhQXgix07vhuxzqjnM
fcNEFFWYZ+6DkCcyq8Bds2nywdjZLCgzWqQQuaz3SDaXTL1a8yz4ugri8RYor73d
lifoQeZyuRYrB+Ez5u+EOuoOuSkTXt7C52fkojfUTDWIWp6Jvlc9Cj7jxz+1C7/8
5kRZP7zH992NeTTHMjmljgIAWpWVF7OZ1m9tzKur1Gcho0BrmwmgIhOqepwEWxk3
VzAC0J+150gH9xEZzefuMPKJQ1qiB6qNKLs74wDz8Towcq+U7baQRqG53huus72m
zUo/REmU1cjlkyp5XVnAYkWCfBd1hX71cC5UVmSIvf5DPKwa4s24ZCAJ3LhWxD/A
UUDOpilyFKvSoZpP3SiCo+Us8nMxqHFRj2mtlome4RCabE6Own0CAwEAAaNFMEMw
DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFGq1
Jsz+9ltLUARQNR5aah5yYxBFMA0GCSqGSIb3DQEBCwUAA4ICAQAy1HA8pVWdWhhk
v/Gy2e3157Ndn3HfWAlgWRwYyJOds+RBMpiUngdddfk1gN9M+zaQ5ng1KfPlHfNY
UbrGacWl0iXWIJjbHvtxK4BfJy3AD9CN8X87+jU+NKmXLUF+V1PJCC0HI1JN2UVT
tfHYuTKS/SIUPflfqb1J7IGNpyoduXxnHQet01Va9eOpwmSfBdF6BbVcgHmaVDsr
uzLp3Ae+/xGy9yLNVQ+qkfWU+ulkEhy+TpF6qo4R6BqabtZL1CbzdeBoZfQxx9yg
kl4MZoy/UF47OUFhwt2Vdzdb56PKP4E9foNJPGCDfhMdyYe5p5zXHWeJo+K1a7dC
/DwoMNSPDDWkWORUeukFVV+l0mqbCDPBnCCzk8Rl4pj0J4ElatjqfcGPUDzwGSCy
YXC5jX8pYexeDBFRfQAKZKqOk9XXVxbDxtT1kJ8zW28OFPMmiVDMNK9J4TlRDgx4
mtM5A9ewlWaKPOpG3B9dxxz08C4DWIf9FOLcl59xDNX/RmRAvHCjpQ93t/Ax3K38
5MQt+kvpPGylXXaDhMvPFrH+0eSywz9aeSgneJDxQt1qu99xGnPZZusY/Zr+Jrv3
me8K40yN93qdEFOFw6qoSSVBGx/8/ukbdkDSUsF4iYA4Ncqa47hj6wJgIop+7JBh
q5/GcQd4/lN8ogaioBQukSq5iqGjGA==
-----END CERTIFICATE-----
`)

func bindingCacheCaCrtBytes() ([]byte, error) {
	return _bindingCacheCaCrt, nil
}

func bindingCacheCaCrt() (*asset, error) {
	bytes, err := bindingCacheCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.crt", size: 1777, mode: os.FileMode(292), modTime: time.Unix(1547750011, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindingCacheCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKwIBAAKCAgEAonvtuQ1kvuK8kuOPo3MU05mxfrYVhvaIkTAs5OlQwwgR1Sqi
dfhZS7Dvn+K0SZGY0H0wa9axBJyEcgLK1ZqQ4YFReuLZMrlGsQ0Rmw7BRDCdyXAR
ntXMepNhcH38dA++WRw2XgQTlEBidJ3nJ0Qdo8SSbok7guDj1aMVa/zZ4HrqwYvO
jOp1vO6ISwmxMKAAPsDj5A23kYFnXJpnGO8CXB3Aheg1UDhJ6ljzIFLTlIryZ9td
qo2H9+JFJzCBZj5M24JvhBGICvZckbi9LNaX/SlSpz6XJjq+YodTzDQhQXgix07v
huxzqjnMfcNEFFWYZ+6DkCcyq8Bds2nywdjZLCgzWqQQuaz3SDaXTL1a8yz4ugri
8RYor73dlifoQeZyuRYrB+Ez5u+EOuoOuSkTXt7C52fkojfUTDWIWp6Jvlc9Cj7j
xz+1C7/85kRZP7zH992NeTTHMjmljgIAWpWVF7OZ1m9tzKur1Gcho0BrmwmgIhOq
epwEWxk3VzAC0J+150gH9xEZzefuMPKJQ1qiB6qNKLs74wDz8Towcq+U7baQRqG5
3huus72mzUo/REmU1cjlkyp5XVnAYkWCfBd1hX71cC5UVmSIvf5DPKwa4s24ZCAJ
3LhWxD/AUUDOpilyFKvSoZpP3SiCo+Us8nMxqHFRj2mtlome4RCabE6Own0CAwEA
AQKCAgEAhB4y4TqjxZcF8IZ6oFQOBjS9n6OdA33o8+1xQ7z3P26LWYJuUXBb43D+
l0o2gG+UC0sQGU+b5n0CMNZWabNhxQtq3nogU99VPNe8jhFEUxcY5ddrbHS57J10
KI04voKiq0CGcJHt/akQpXRTpZj8ZNKMoraRnk0Q1QDjhUg3PRGVW0U78Vcf3z0x
s5ow6rHfISek5iXFMto+2oxt8lc92vsSNY/n8c+jQpuLLahLhEgq7QnxMqIcghIJ
WuFVBnb39bEszf2XWhqSkKbfo9rmASMdowIA00QG1ITnPW7R77MozFlB6LrRHgQb
Y9NnwwUKhM/rSEanLAKh7iXjD34srzAOjMWYBoVWdk1A9Z/lq1LiUDxusnBXjP15
yXX1OJ5aDUYbJFfyUhWzNLGTpVx8f48Ym8ldrmWGjFJYsbQ2vyD2bc3k6wji3QHY
dHIcWNjiSek/IQtlwBOxsRmgOLot+zKjUgcYu4ZPlcxBUUoU5VXEWfaayBjgTxnL
p/6mrBgBMrZDjZc+gbypznEsJ0kbrrPPCCsJ6a30/9ox6zJYlfskevxRhaBzBAj+
uZPQi38SaTpMARez+OlRJm8AVDIitaUTG0MH2QfAkHMAs9kNpRM0CdpMss99Xfor
kwD5n/oOkBqpY3uM6Sw/pYrWZkq8bWdGt8NULTZsuysDdzShU90CggEBAMM0est9
wvQj7T+C6VvbF+yJGsrA7I0IgbKDp4IHk11ROMnBXpx4PMKyn5W88XSDiKvOFTb/
Fp+IbTF5Y/FJwbO7ZrCO9TJY5pYp7Y6HOe3g4HMYn1ULyC0bFm1fJu5rhw5VGCH6
BxoRUXEZXMsV+q0L+3NrXh9fCCO+9rIk0HpYWpL+pYjxz8/gs4IiMcBwbk/az+PD
IBfXlYWYSjU0S5JcKNcDPR83aErKnMTqImQcIMOjWBUBC7VUtcoRbRsK6lpJwC66
XQUPo8htMTk0VhdUz7L0IFM6z/Z7+OORXmx1RCdlzF5M3IBIf3rdfEl2BQNlc6R0
+rIgVKAIPLk3Eh8CggEBANUWo/zPwzY5bXFTWs+sPU7jX6u/WV+9Rg34daG891Ps
ZRLQz3W2HbEZosz1472kX6I2EcgV7+MKvoDANiNQxnI9IB3+/11I0vMA5q7U4tWD
KOeUwMQIguIs8uIWdfNyRYqx9X5eHf7jmpLOJ2YK39B8dXlfs/fSsqihqxJ69nGF
kD7Y54/Bc491SNmQYEfmyFXBL8qNq3GWxkWAzJmzV5bs71t/nlvJ3kSs+R+Wk2II
4hQfBAHq3MTyuY2aFDIz0A9tuBtfcSSqHdbia6efPk1ql+XUpCriSiet+rZod+ZY
67O2mPps/BtjqgbDJ9Bk+n5bLnF7ppNoWLOy8XjaL+MCggEBALaoCK8ZAq+IXpur
V8kH/h7rPBK066QcbaAo6TkW9aHAOq8vLeSj7dcRZZqrrhQkcGKy9876aqTk96fv
usExDvurQ6+6VV3DKiEhIpTXnDEm119bjtv5plnumtHE050NKNcUcPx6BOMziU2X
Oekeq+345FVgBja8qdUo/5Y6NIoG2tnpReQawSX3UIFYlc1IZzB5w0WQdBtbMyJL
GkUmpgBSFDT9Ztgq9H/nj0IDBCNA3rexxN4CmH4YwfJO1BUV5ayOjjIrWJc/xzXo
VsL8YgJ67c65+PVoduhhoMbwY7aBFED5VH541WuEayUA0ye6M362E7uzalH7RrRo
gMme6mkCggEBAIXScC5nNEuriSXwmUlu/Bm9BepQg4pyzbocXZOznwgfn+JPLNra
Ao+kb++URPBmeIDgwA4OaNcHelhVXiqToe1Aohj0ed9VytU9raICpGo+ssOtUdpL
FheA7xA51t2K2E2gMXKpHOFkg0DLI0cccS732rbc+aMbuYPZ9BvpCTiGDu7JPbO0
ZCSmHZg06aJ+NzZT2vW0PwVZES+5EcU9Mjbgmfm2jfdLMcGjd9j0sZ6RwZmtWNDz
dK5jWVCqgSB+FZ5643KdX+sMwyyeicl9Yp0v4jE+d9NOxg9hXeCMfzA0i+ITPMOZ
CkMRNkiE604e/Im6LdKrOxO8JmjEao3hSM0CggEBAK0bg4B+LP9467+Q2es1BEAi
NNT90LmYpCVCDCqi2eiLyH3nN72QHQXy5AF1OXvJWj7AHw/aPFOGpiY+rQsFJwV0
sTvFM/kiLiNFNe5T+2XT37QJOCHtEWEVAHAk462MvBQEb5POo11GN33N0Yz9DPBM
vVekD/odHstedVQ1L04t2BgBUc8GRv6OaNtl0C37KyqWwYffZyMrduiSRENbaM8k
0J2ZKNmDmGeG417w3/u1wezIJd8l5fwqhGvYiU0LmAVlihRZ5oOMStWiR1bwJeeU
dduI3DK1VicxiUc68tNOlJCMTlzKVXBjCGW3UbDs68E2uv2yfcd5MeOt871V/8o=
-----END RSA PRIVATE KEY-----
`)

func bindingCacheCaKeyBytes() ([]byte, error) {
	return _bindingCacheCaKey, nil
}

func bindingCacheCaKey() (*asset, error) {
	bytes, err := bindingCacheCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.key", size: 3247, mode: os.FileMode(288), modTime: time.Unix(1547750011, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICgDBqAgEBMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMTBmNhcGlDQRcNMTkw
MTE3MTgzMzI4WhcNNDQwMTE3MTgzMzI2WjAAoCMwITAfBgNVHSMEGDAWgBSnhYiL
nVu0m9mdMuI+/oLzokwgszANBgkqhkiG9w0BAQsFAAOCAgEAQ/u7n9qBsy4JVxW+
Cx/mEU3iGof07u9Sz6WZSmdCxhvHvl+c1Ju/9kUlEF5cpxrx78PPFMiydJuY6Ekj
wtMYRtP1pvJxPZJYDHG1e6jDZ/v5MYvAyq2C9V07s99TcT/WCBR4F3oH49zmN6SM
RX+9Dzlq0725CmNKSbn2Ej6+Ob05ICv2ck6DdLCNkGqFFer1FcGZR5YTf3u8UcAv
PKggIc9/gBzj+lGpooCn9m4BSLIkhrRleeitC//qEqPFIq6ATWmzSxtnKkl+aIGb
sf82TRUV4mnRVUnisu5RwdIpzqSeliEczbrvL10hZkhKTLeO3qb4D76F2CRhIVRC
ilyVTSmuHg9iBIwIq7dBLk+UNGlZM2LVBtXUzBADbN7PcZGZqGEV/gzdsAqwAVlK
co9cs0c93iTv5tAroTvnHBUbuM2Zy56O2MScKrrr8zd9BBx8v9grwT8P1izHw7JF
isRhuCQEatESXUBeZUo8UOU8etM2HLo+VgJlRWD7PwvZ/w+eVdH1WAQCYnVe2EAW
FtXRaYhi38aSmGotDRoaHhw928h6cHjJ4be79WkCkXKLeqNC5s6G+IgZQ6JaSudI
xzMstS4GWPNFRDzRKqu6/C8Un65Z+RK26QYaukdx8+cJlYoX/DeVah4M1g9ZDgrr
2X8bwDfuP/AStAj/fYUbFRg0HgI=
-----END X509 CRL-----
`)

func capiCaCrlBytes() ([]byte, error) {
	return _capiCaCrl, nil
}

func capiCaCrl() (*asset, error) {
	bytes, err := capiCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crl", size: 922, mode: os.FileMode(292), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZjYXBp
Q0EwHhcNMTkwMTE3MTgzMzI2WhcNNDQwMTE3MTgzMzI2WjARMQ8wDQYDVQQDEwZj
YXBpQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDyU9qYWGoLzRsm
XF2rdExH82rUkJONhf/REWu9/IpiwtEZwuxkiWvrB8kgYwSxKLuACA1OB3ngrsRt
5obNiy7nmpgz+Q6YIu0ns3E2XHULKpyZQ7Z2wmxjak3oosz0ZwNjKwR7P3Mz4+r8
nGuf7PDkZjGhx3SfbTG2MIEUX2J5MOlEZQGI6oKDCyQbonVn6hwHY8/XW5LyG/6W
/GHIYvdSWMA7m+zGuJ6AZ83tXyza6+5gUYuNn8Fh5x38QUWLEHR4KT2eNO7mgSKR
IJB9uWTf5L1R42WVQcXYxB67yD4s+qyxDIh0elHqkSLFFswu874gBP30ozDP2YwW
1JcgHJhvDqEmj0zZAz0kDarorShKrJnOi3qeeiEHz3te09iGvoB0x88LFfysi9DY
xEX0SVNk3YfnYgVDBli7wTlK2HcKIy+MsgpQfp0INUaoRb4q3eYfQmSm5EpxDYDZ
O4DGnsis1G+c0J3OVlTsqLt0gQ0NKhY8neI/6qANSYelyztQSJQHv4o8HQc4goOF
V8K007CD7s3tGLSHmprcQHICzT+eq4KaQToEEXm76bYYdcurt9CFmI1bC+Fb9C0R
6vHQlu19ThzOajZBPhE68FWK1WJ1Zx/NSMg1Lp6GibLS+nWBreMQ+3jRfk70Fccl
An4PkP/ybYqtK2iB/H7wPbAfBuxSVQIDAQABo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUp4WIi51btJvZnTLiPv6C86JM
ILMwDQYJKoZIhvcNAQELBQADggIBAHsVmM5GoaH80bZQk4qQGUMjrI7U1Pp/BijZ
1KRKInS7eiIYR4srm1UvaFKgoG+6O1Lc/IwUzCRaVTqvO7Wr4A8DPxt1P9PuZMrA
gc2reFDQoT3vkrsJuIDNcs9CI9mqPA3PJS2wkI8VOp6O7RRsCtMyvG/CPJRUW+Gv
HpLaR93o73LoaKnuU6Dc06LsnU3Y/brnsq9teObJQQcZBvYwMHf26QKjd71Ch53e
LFrgWvdShdMhCk0SGf3120p6njHOV9TpHTWdL/At5gAx26SDmQYyV39m3Sb949qN
sWb6G0Nb/0ljZ4SqmlAA2uCn8BPRTKBAcyE1Xj35kmd87h9QJtaheYZ5AfRF+pSB
3CsZdtj0w+LuQ+nX9jTCbmfYbJo8my3moTlGjAneN3yz9PJ7sUo4/DMia3Pcdub6
Yytvum5+yy0pH6wtISgFN3mAgkfOhnfBBrYqjRk4mKO2LpoINmsEJap4bUzMxhZp
7xXl5MtcICsdgPWNa45m6nBagpSXzPnINrHdkx10dWqs8uzSCFUIPXS14znm0g0h
Z4an5tPO3WoVRPFJHI0ycWcPqIGi6vcXqIEBElwXAAR7UsXAbxdjEQaxwARYcg37
hWhSa7VtN8dFivW1RjHDy5py2Ko3ElWorbI5Dx79YCy/rgUXV5nTF8fVAK4g4qh1
gSgU+EA3
-----END CERTIFICATE-----
`)

func capiCaCrtBytes() ([]byte, error) {
	return _capiCaCrt, nil
}

func capiCaCrt() (*asset, error) {
	bytes, err := capiCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crt", size: 1753, mode: os.FileMode(292), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEA8lPamFhqC80bJlxdq3RMR/Nq1JCTjYX/0RFrvfyKYsLRGcLs
ZIlr6wfJIGMEsSi7gAgNTgd54K7EbeaGzYsu55qYM/kOmCLtJ7NxNlx1CyqcmUO2
dsJsY2pN6KLM9GcDYysEez9zM+Pq/Jxrn+zw5GYxocd0n20xtjCBFF9ieTDpRGUB
iOqCgwskG6J1Z+ocB2PP11uS8hv+lvxhyGL3UljAO5vsxriegGfN7V8s2uvuYFGL
jZ/BYecd/EFFixB0eCk9njTu5oEikSCQfblk3+S9UeNllUHF2MQeu8g+LPqssQyI
dHpR6pEixRbMLvO+IAT99KMwz9mMFtSXIByYbw6hJo9M2QM9JA2q6K0oSqyZzot6
nnohB897XtPYhr6AdMfPCxX8rIvQ2MRF9ElTZN2H52IFQwZYu8E5Sth3CiMvjLIK
UH6dCDVGqEW+Kt3mH0JkpuRKcQ2A2TuAxp7IrNRvnNCdzlZU7Ki7dIENDSoWPJ3i
P+qgDUmHpcs7UEiUB7+KPB0HOIKDhVfCtNOwg+7N7Ri0h5qa3EByAs0/nquCmkE6
BBF5u+m2GHXLq7fQhZiNWwvhW/QtEerx0JbtfU4czmo2QT4ROvBVitVidWcfzUjI
NS6ehomy0vp1ga3jEPt40X5O9BXHJQJ+D5D/8m2KrStogfx+8D2wHwbsUlUCAwEA
AQKCAgAgHutXzEhqPgq+P/oOkwDVfLeJa4yTctKg9M0yRrpVMvuijYrmHK0YX1TS
nS1vCjYoV2jkEeue06un4am2rx9Nhdls8jN0CRUkcQ2tpf3BuCk/y5DxFv5lAx9G
meXO86SoTXhvmc58b1ajm1xMu4yGyeEET7rusvum6bECcU5NQCV7cmQMsQERu7VS
kGs9lfOXKyzOoA3PV9ScUOHpPO0JlkgM3rM4+BnSbXAHadk5P5K+Y7C62hU5E/iO
ilxcfZbiopzPTrboCO/7CrT8ZUmwv9I0e47ohOpjvENSos1TCvs/EKk5v0kCbbCN
LWNtSdPGzMKY3dTHiE+gaxeJIyE1PVIjuDr7q1YKkwCEztkq6lpYjC+qGFFo+pyP
i+idZ7RN25dKiyVnULADyHO/Pmxj5dFsd1Ud7Kh4hrUN04VVy4Jz3nNuqBifHFH0
HnxB1rFiZ8btctQtZtBJoyWM1oMNOgi9GcX7+NqYzbhGsl/vNdg0ou2oj1sSorFe
/lptO5Rp3WZSY7UBaxcUydslXnVaP5443pKY/AAjJ7VnPC+k07jU2l4qa9pZXGiC
Xc+sQ5NCrP44K3DacPyJWrRXa9NjGthAz80Lz1zHyfOGangmOIs7TJRPuw99nvlY
LC5W+v3+SSgwwsHgxpD+dQ3X++ihzSrBluF4UKE2FG4tL3LwNQKCAQEA9O5X/WPC
uiyc4aokoLXcb1dJ6xCuh1f7qn+98XbxpwxuHT+xoXYiBDvR9OpeH7JE+sfptemI
NNGWwNaxGI+6uHbweyz3dUwoom12fPlwwVlJkYcxhYqTujHEhjKCJcgX0SVaqtte
pLWO5sF/wZAm9/+q3C4IT4cOWYNNKe81UB0eCHYQ9pfkCihiiOh45yTb61QHbz4n
msBaA7sRoaMHBp4il0uaw1Hv/QJQOjRcQLWPX+BekxKa4C+YBUPYrREOcoZunBoX
8PDUX+MRjhekEHEV6jZy4gXtci3pFfs3Zetnuw8UTlKB3wa+Jg6k4JdBVMa0MA7v
3r4FHsadBP70JwKCAQEA/Udj2cP1au7vhX+jCDvNLJKPR2F4qDaL88hga8q4PTZF
cGIUoaUHPbjoB78Vfpmoy0hs7Rm34M+TH4Ri3F289XwgxSnCMmNQpi2rid6uD17r
K1RrYx84ceC0emQazRxoqLPQQ1CTCEZokEnsayDKUv4+NQnIH3wSbHc6FBjt6WqF
0dTYXrWrZt2wSsXdOKS+SxKfS5a+0GeDzbd5Y8EavgozYKP6YdkEzrxdR3dN9HtZ
OxhlqG3r5tgCt1VSLFHt5KdFMVZf7ORO6IWPHYwK3yvJ6UNzKcG/H4GjYupbc7Nf
XhqlUZ8Kyv0yQcV3TyvntZW2gn6UFnWLYq8caIknIwKCAQATknw7hl5ILEp5CfSV
VxL/XrVMcG/R5uj4be7Kvdt/otGlyrIyGdOMDQ+xB41v8PnsJE97tuaoedsXG9DZ
Cps8JF0BKs23dNeGa0Ldp70n5i+nzmrZpgI6DcILizu1MzEcCGUfZBpDBTMfI3VH
DXLfvHF12MPXPw6ZfpGK+U+EUF9XA8BFREv3t9Rv5kvLBLoCKxvQ+uGFTzuiMq+s
/+8Oy1IuTt9WHlUUHbw1enuovBlx6ucDz6fKpGL8gLhu0/8Yjb+G/9rL6SK/atC7
Tw5QNgkvRxyVDS41Qo/urr11ioMmgoT34UX5gXtuZRsty0hwMtSxRnBKl1qnY+2m
OY1fAoIBACy6zOGKf+8Qn3BeKDauCQAUKgWbKynZ6EF3Y7/ln0AAM6czSx14/Zxi
6Wdk0bD4Bh1QfxwobJbhUcRBJwxv6Y0ZDNiFFWy8qWOPsTm5/9drFfEjCYwJ2XgT
DQyIXUtX9wvEJcWdlzng5VqGE6Cfu9uIVwga4CLfUImjTLh75phQXa2+/y9KuiiC
gj3ST81PGuQ7N7KrvqsjfN15x5BcbBKfzo8EppVdNEImdfrHERdaKVoMZvel4gF0
qJYkFU0Kcw7sk4WxEWPOtjjOTYYUU18yZogxh0callxEEszHQrteNDt0TTnq8ocC
zDtdWkK7KEKjXAYTwKduvt0Au+2iOy0CggEAb44phu/pdz2aLSxJwF7o4gPC5vkC
wWSAzUp8fLElM/JL4Zobzo8CtgXqmDI0ymozcHd0AEHlcwp9HMaZUjzL6AqZw9GF
F2E9/lzH8nm16VGBCzDskqt+/cVwls2zmMNI4SvnyxC3ck4lVthPwCmZqaEdUNHJ
Bd2ZFg2pZB1XBggQbpwp56PaN1x2UiWaVYVMUnSXi8QDcQkXLpu327x3j3WQptB/
Gd8ho4EDkYKoTN2tsxdCFDSeOLisiZ921wPOVjeU8WzwKnn+IOlzJNgmyCwYt9qb
uAOYwdEb2mDQmXTpw26JY7FamM1U5gahV6gqALc5Op6bwOw1QJdQJdMeNQ==
-----END RSA PRIVATE KEY-----
`)

func capiCaKeyBytes() ([]byte, error) {
	return _capiCaKey, nil
}

func capiCaKey() (*asset, error) {
	bytes, err := capiCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJjCCAg6gAwIBAgIRAKgQLxeauCC8AvYzE1/8qHQwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xOTAxMTcxODMzMjVaFw00NDAx
MTcxODMzMjJaMBIxEDAOBgNVBAMTB2RvcHBsZXIwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDWSW7/m1ow/36Kls00U0xBR1FRdxae0yk/Upjke64glZpB
r3iHtHSbchKyi7EmYw3cm9/B+3OFEDjNdaLlrluw36FUYucTzaFt79Tkd97rnbqB
OqKjOdAJOz73aZ1/C5FrovjwYNT5snlsZbcyk/hfhWYIzyydkXBNcUudvWmXWTiO
NrD4qUJdXFfibR9lvO8tqNco37tVoOVGZxls2+0EUiuown48pydghtcLBxjE6Nen
d6OLwuoxDAHN+bS9cBhPkQ0eb3h1QkWDVNkF/Q0WjSRXa5NMrNR/QN2Zztxrgia2
Ktz/EoGLSFDAqMrUOFn0YwF48+6gUgNAQ8gdECijAgMBAAGjcTBvMA4GA1UdDwEB
/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYE
FMLS5QmNn6yJzWCFtXi5M3lBWYrzMB8GA1UdIwQYMBaAFO9CICNMT7DDuNA+QHz9
bfePdFE8MA0GCSqGSIb3DQEBCwUAA4ICAQBXdDVzOo40vOEeqMJnc8Xh0R2Zpli/
CQF4PLbJqoEJSDANyBPZX2PDA20ZcsIdD5hiKocyZdrc1RWc07nPkWg/pjVGEBeJ
5KPFST/VyErSCck4lmk0PLdsKYwI9WJv49BGae+GCkuhcSXr+ul/GufLb3e+RoBb
04QFaLa+0uazJxy8g1Yj1D6RrvwxzvGvBOnz+8jJFlSlt4xjZ1o+V+d3ZpCVS9G8
Hz71G7I/lg2yFk+hDKJIY8N50J4H/VqScrekZQlNPnuQCQ+WDm3gcA5skuMuHaHY
xDGd8MsV9HlKnUmypEhyibj0A3xeT4fsW8v3kOpZeyq4fG65XkT+HUsCzs7euMRn
Wwjlc5xVRfRvULEDZpLUXOoSciYpX8Xee9pL5MmxnPDO6K7xcvoZYKG3WgtQyfMW
aaD12+/fRjOyQb94FrovoZR+vFYEv29+Ul1EHraZYbO8LlR7GpN6vSyIAhK3MAFt
PZkPwCUDDEEALANIPm9ROkXSCGJwkXixWPVJpeQobv8EgpqxzuLRUoiQb/e6LOec
NV2x7zA4iCvxf0v34S0IsmRUozNIvQpxdqQLIKAYUS78dWzdlUc1RWf/TAD2J9Uz
mcYtfL46HvZOhjD35ViOvbRLB5SAfSxAilDgMmEbi0IyZ1fVmfP/rF4K1xfni8bs
OG6slb6UDqKysQ==
-----END CERTIFICATE-----
`)

func dopplerCrtBytes() ([]byte, error) {
	return _dopplerCrt, nil
}

func dopplerCrt() (*asset, error) {
	bytes, err := dopplerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.crt", size: 1501, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVzCCAT8CAQAwEjEQMA4GA1UEAxMHZG9wcGxlcjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANZJbv+bWjD/foqWzTRTTEFHUVF3Fp7TKT9SmOR7riCV
mkGveIe0dJtyErKLsSZjDdyb38H7c4UQOM11ouWuW7DfoVRi5xPNoW3v1OR33uud
uoE6oqM50Ak7PvdpnX8LkWui+PBg1PmyeWxltzKT+F+FZgjPLJ2RcE1xS529aZdZ
OI42sPipQl1cV+JtH2W87y2o1yjfu1Wg5UZnGWzb7QRSK6jCfjynJ2CG1wsHGMTo
16d3o4vC6jEMAc35tL1wGE+RDR5veHVCRYNU2QX9DRaNJFdrk0ys1H9A3ZnO3GuC
JrYq3P8SgYtIUMCoytQ4WfRjAXjz7qBSA0BDyB0QKKMCAwEAAaAAMA0GCSqGSIb3
DQEBCwUAA4IBAQCIxQSvhIPKdNpp5eoCqqYTip6zVoj7d0V3ZzrVAziw7uMW2dSy
mOcwv7OpTQ+dUPyHrclYtM550foNIHdnLL1XzR3OR7UPtICT7BAnIqpnuYNEdH7e
IhyZ05gIpawjxu03CiN3LBH4/0deUNan49BTiVmCKexpRaIOgz7Z/hEuJaJa0bSz
eGt4wHncvEFZOkemp6o/rXozzds7hb3YzZeOhuAr8JnX92mjf2BLe/qerPfXI0uV
/Eg/IJn59jiPe8JoydRwhuSk2bJZ51GoqMSrRUOOOc5M+BGfx5HiQ6J4mh7/2yhT
4Jmr9pd1v75kmJaiDgXbwrlceAKv9euNqT2D
-----END CERTIFICATE REQUEST-----
`)

func dopplerCsrBytes() ([]byte, error) {
	return _dopplerCsr, nil
}

func dopplerCsr() (*asset, error) {
	bytes, err := dopplerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA1klu/5taMP9+ipbNNFNMQUdRUXcWntMpP1KY5HuuIJWaQa94
h7R0m3ISsouxJmMN3JvfwftzhRA4zXWi5a5bsN+hVGLnE82hbe/U5Hfe6526gTqi
oznQCTs+92mdfwuRa6L48GDU+bJ5bGW3MpP4X4VmCM8snZFwTXFLnb1pl1k4jjaw
+KlCXVxX4m0fZbzvLajXKN+7VaDlRmcZbNvtBFIrqMJ+PKcnYIbXCwcYxOjXp3ej
i8LqMQwBzfm0vXAYT5ENHm94dUJFg1TZBf0NFo0kV2uTTKzUf0Ddmc7ca4Imtirc
/xKBi0hQwKjK1DhZ9GMBePPuoFIDQEPIHRAoowIDAQABAoIBAQDNO6fDx9ap9woL
UkNXSjBOlS+dBqHzm+p1a3Zj3tD3BFGpd5XI41yLRMYDmycfzN8J24CDGYGaf97n
aTOLJ2NKE+VAHTmUDe3+jSUpbGVk5Lwr6Sy7iDNnpAa6j7z4YOv2WzBxiUxxmi4R
U5oSJwZK9kizRzlD8HfOtCPn//GRsXGC7TfNDVWwolkSoGew75T6cYAaikNXK6xq
YsO4tKdEL86KTO8DwUgy0Yf39DHYCXKix+1X8/DO8M9erQkMfCd7B2iCwJY2RJCo
eT9EF73FJXlmkS1m4ZSeVi4UyNUtzb+1Ax58Z1sw2q5tPhGifiSOxgjM8mrlnP5C
/lwzcK4BAoGBAOmi99d5BdZa5JqDD4C5g7RErLtrnDbJ+1ysP7/0Grr/AWtdGi8y
yRmQqcOx6FzHz5iUm97o9xyyA36KoXBf7zbs8N/9bMK/GSILu1+lUdlEgpS6A1VP
OB/8tP2YcFNOnK3MEeJNWMgEjZnC9r0w4roqSEvPmsAFmPP6OTw/PCezAoGBAOrM
Ubrqs+uotSvlbbItyuxM/wB6duINP9mPdH1yQpk4USGuif3sG/+ieIl9Bs+EAJns
94Bg4dLV4fQHIMSOCGa9VhiY2V234O/ck1+tcltQKxCDENkSNiSOHjGpT3xtFZOH
F6juIP6IqcBKUhDmBvYzg98m/GvILJzQdp0m7YNRAoGAQnq0uwMcvhmu4qhYSPCA
oVLJM6szEAP5Gi2JFj2HPZ5B8SLUyIlS34tiQuTkkUHpuCjREWSIrAmbJO6dcTRb
BO32vEWIJQHrTNy5vEV2PLRZ06f6OtQHzFJDzcUKcSn1Ox7OF+6aTI+/Gvl26+51
FTPizm+MQQdWtlWE47e6jjECgYB4wuuKUmqFWzkLQa4gxVKoJJXG/jWk4CGl2RWV
6617Nq7rvuR0N/rSiRKrzCUzl/XjNTC605lyIdVb+EqPLWn+xYTBk+PAQvGrDGyz
+fZmJp5vmKmSq74zIPFAo48hNM2zGfk+RnOr1khQgSkiTdzoxegeXuPW35aqdMF8
5GemcQKBgGH7771CXbJIjG9ocdYpgMJLNuaRyfvl1CC14Cz3xQ9cryWYR7rqvJQ/
XkAdxCw6BDEwmam5+cNaXjNJVuwq/sENnxSM3qMhVYTcIzXLtQD7ZBu+Ra3xSx5u
AwdhqFar5FfVxq9axmV3csN3n/G5CGTU6RbSkLWBaraIU/LXmxaF
-----END RSA PRIVATE KEY-----
`)

func dopplerKeyBytes() ([]byte, error) {
	return _dopplerKey, nil
}

func dopplerKey() (*asset, error) {
	bytes, err := dopplerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _expvarForwarderCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIELjCCAhagAwIBAgIQDVajP7xw/L72KAUbuyCMnDANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE5MDExNzE4MzMyNloXDTQ0MDEx
NzE4MzMyMlowGzEZMBcGA1UEAxMQZXhwdmFyLWZvcndhcmRlcjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAOOsigsuRDWWWOyD5zHXWNPUr4p8JWO1jkWN
2HhDZr3xBnnIR6bjQs0emGpfMq0zm6qjWkqY90XXacDSFlCRZcA8WasPXO4LCTjN
Ey9dJUJxkP4260zVQucqWLpmB8GGzf0oYcFkgAC0yJZxuypDfqWgpImSWdRwE1Nt
KsTn7IGsUXQmlDIdvaSMGaj5r7Nz1VxsvTxqSYHRl7WbjD8CTg6lgr1+LfPKpd50
xrXNkVweVrUOExsIOeZYtfbKdoPWILsZDvA73bLR4PNStigfNZOpJIxsSNYZhQ2z
TV+e1FXXSzAFlHK5aPZHObZjLci0WFJGaQYPMen3hWMn0dZ3l08CAwEAAaNxMG8w
DgYDVR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAd
BgNVHQ4EFgQUiqrb0N7sKVZHeHhVp2ZqGu/PzMMwHwYDVR0jBBgwFoAU70IgI0xP
sMO40D5AfP1t9490UTwwDQYJKoZIhvcNAQELBQADggIBADQrKonW8+5lpWGjZ8qS
ZmV6N3H8HibgWWdAama0vbNtQYs993fsLgEi1mTrSvm9u/OL3kH7grg4W80/kJu+
g3iJp/57LBhiajSMKmeNa2GA+JyLbcVBMD+8bhbKz+eTELFgKjxClos7NS1DxDq9
Rx7/m1MTN0TPSifkryOPvGUmi+EbswwpbTdPd5fqkrgXUVlDrkUtTRal5ZV9esgD
n9I4bYIpR8fzsRgTvVSf/ckVE1m4/N853EEAuRHxm/dEaNDQBwS66j0+8wql3rD1
/w6lB3+uLA9iiG5Csr+E2CQ/32rF3hqf06S6pZ8wy79h6EHUPY9JJqlguWKppG4h
mhBAM3AKOGK3ACyKGohi47smzFGWxvBAkD6ihIqg6QqK/Q4mw6g+l/yYHkSUPm/4
EpH2QUPFamXyf7908I8/Y8depJZoh3wIpEGv37rMZTHc1K7aJ3dGUryAkdA2bZ9J
PzKGrQyYwmNDkTV3ndcd3zjmgAbNKhqH/OphKqLIYg/G5HsUiN48dyNEPKMP/XL7
pZLgqS+PpzpkJNGoOqEL2ksg0aJzSMARUNLzLeyVivLZR2vb8OaZOMOwd9Ift7ZN
c8ETV7nNbn4VfJzMHFbt/hAy4BS04etA8XtzcZRhV2HLuFYjM0LIZSRqoVKutC43
zEh7nNf59ZgtH0sfOyb1n9Uj
-----END CERTIFICATE-----
`)

func expvarForwarderCrtBytes() ([]byte, error) {
	return _expvarForwarderCrt, nil
}

func expvarForwarderCrt() (*asset, error) {
	bytes, err := expvarForwarderCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "expvar-forwarder.crt", size: 1509, mode: os.FileMode(292), modTime: time.Unix(1547750006, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _expvarForwarderCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICYDCCAUgCAQAwGzEZMBcGA1UEAxMQZXhwdmFyLWZvcndhcmRlcjCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOOsigsuRDWWWOyD5zHXWNPUr4p8JWO1
jkWN2HhDZr3xBnnIR6bjQs0emGpfMq0zm6qjWkqY90XXacDSFlCRZcA8WasPXO4L
CTjNEy9dJUJxkP4260zVQucqWLpmB8GGzf0oYcFkgAC0yJZxuypDfqWgpImSWdRw
E1NtKsTn7IGsUXQmlDIdvaSMGaj5r7Nz1VxsvTxqSYHRl7WbjD8CTg6lgr1+LfPK
pd50xrXNkVweVrUOExsIOeZYtfbKdoPWILsZDvA73bLR4PNStigfNZOpJIxsSNYZ
hQ2zTV+e1FXXSzAFlHK5aPZHObZjLci0WFJGaQYPMen3hWMn0dZ3l08CAwEAAaAA
MA0GCSqGSIb3DQEBCwUAA4IBAQBZnSvqPEf5Ph3+TjMLA4a4ENwS582+GjYUJPtq
ykdW+lYxohoB0D3cPKtg5Cpa8/lC6Ulv4b8lWGOZPsEEkb3npUPZ7QnIIRKgbYSl
beD/WY3e7UwZfUxZCusI89f4HfpvMzNvGpm3hVLLBowBK+amSd28eoYoOJFONIO/
+NIGwmEy8zhfdkzUNEwd3dsTEb/+rRxxvwYospqT2Yj7VPH8tFZhI6kbmf5mVwEy
Yo7CT/YWchnQg204GMyrte5YT/qcc3ps2YnSUt1ccZzK+Z83yL9GmHZgczM03e2H
rlKgJyxUUC1ozxWNAjaw3Y5F+NpHyccE3Sv28Tt4hLx/Hl4e
-----END CERTIFICATE REQUEST-----
`)

func expvarForwarderCsrBytes() ([]byte, error) {
	return _expvarForwarderCsr, nil
}

func expvarForwarderCsr() (*asset, error) {
	bytes, err := expvarForwarderCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "expvar-forwarder.csr", size: 899, mode: os.FileMode(292), modTime: time.Unix(1547750006, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _expvarForwarderKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEA46yKCy5ENZZY7IPnMddY09SvinwlY7WORY3YeENmvfEGechH
puNCzR6Yal8yrTObqqNaSpj3RddpwNIWUJFlwDxZqw9c7gsJOM0TL10lQnGQ/jbr
TNVC5ypYumYHwYbN/ShhwWSAALTIlnG7KkN+paCkiZJZ1HATU20qxOfsgaxRdCaU
Mh29pIwZqPmvs3PVXGy9PGpJgdGXtZuMPwJODqWCvX4t88ql3nTGtc2RXB5WtQ4T
Gwg55li19sp2g9YguxkO8DvdstHg81K2KB81k6kkjGxI1hmFDbNNX57UVddLMAWU
crlo9kc5tmMtyLRYUkZpBg8x6feFYyfR1neXTwIDAQABAoIBAQCmXmSZevuY9P6S
BmkhQK3GTXrhBYsE65zFMrvmVcp0LfZ/c1z4lMUxwpO510reygGMlcXbESBQRvMe
Vea8hSMHcJJNr/JGeIYKncDRMY2Smg5L1bHn+UbkSUuBGiG8x1crESEuAtSOr4yM
cxtD7QJU4aiaZvmBhUx6ACHqtVdcAUBHdbOvQdkBHw9smgy1jDhleunWzrILR+Q6
kyokkEE5NXp7M2ri2nc8sc/8ZRaL7R3squVedcd1spLOq8IkikqEyHUglQ1tplY6
ieESVjXF9L+hAjUK7ozai6r5JuLWadjSgseW0V9gA9VtPoo0sDhB/uPItixeVIHN
LZkbt2lxAoGBAOTy8vgdTmPbSpnkkLOv5MfKISXr6FK9wNtHHJI+WAplDd1yqonr
Uvi6V7TszNVb5kj7OU6r82p3liKCqvy+KLe1095UYR68XkNvUIpXw5SEaMB+FCzv
N4pxkeUH+ubBg4VsI1yWnFegFveryDFnMiTSBFkVihtMNsoijm3n8pULAoGBAP6T
BhzXMEaD909m9h9JRVvtutYYMcaPPZwI7uNLx3PMBl10Z7v9k59gFdwoO+pn4d93
ZE6GQ6jO6o7p9T3AGCJuh8DpobragZQfxzjd3V2pXKZabyB1/zL1CRO6YnzKlMzf
dVQASY15n45WqZ1EBSQ7nVg5gjpgH9Fn957rJilNAoGBAI+dbpgBGik9Z+B9Jd/x
WBuTSZPWFZfBe/aQ9vUtsmBi332n7h4xxYxMp7PQTvUPfrcND/evmTOR7FWdjdCZ
IEWNA2gVmg6DrsWyT91YDFFfda456EH/lOF9OD1o8hRKE0xgdxYfS9cTjxSxZxTG
XQgHzb5r6oQRHNVTM/DxbJPdAoGALq/h+BoS1WvQSDSWwKgcWz6e/DKVtleAsgQF
Y5P7MSZiqHL3r0dS8nCZsbWDP3rrtqLbt3byI5xG8gzAGCIJiw8AQIXYTj9Sckrd
q3Us6sdroWqGZMqfEcZUctTEySQR4/y7NLuUwahjdaQ5GQlnc/ym3440buZAD5Rk
mjV/2yUCgYEAgx4cYSB35UNQcjo/zKeed6KEdFdgdT/V8TtO88nCcLpo7BMqK7cs
NADEeHKzqq8/upFpIpvUTEeMNMo7XLRFcNIvXuUlJOSXrij+AozuGNV3j/nAghN/
6rniuG7ZlpB9WGCJwDQo7+v6infAZ/D0Yza71b4NNafauYRzH5aA32g=
-----END RSA PRIVATE KEY-----
`)

func expvarForwarderKeyBytes() ([]byte, error) {
	return _expvarForwarderKey, nil
}

func expvarForwarderKey() (*asset, error) {
	bytes, err := expvarForwarderKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "expvar-forwarder.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1547750006, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEITCCAgmgAwIBAgIRAPGrsHm4PmBe3XX7y+JYb5swDQYJKoZIhvcNAQELBQAw
ETEPMA0GA1UEAxMGY2FwaUNBMB4XDTE5MDExNzE4MzMyOFoXDTQ0MDExNzE4MzMy
NVowFDESMBAGA1UEAxMJZm9yd2FyZGVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEA2FLNjJwGLu9CkOX28/X1zlfv/7YmHYS4/KAVnPIM+rOgBZtWGkSd
x3qAkOWWj/h/cr4gZynSo8qGPvf0KxFdjCP1I/HG9erTFdSI7tdFn8eTmZPheqfJ
h6wfW6SG+SNz38AqLhl0GPFNpnjYD5zl7/iAQozolF1G/+l5Jm1HDhR3l4JgX5Ka
VZEdbNW5uIadCZdipd94i+1VK4db0w1XP/wfz+c5Tisu8f4LbhCGiXm4Jzwey9j1
k/R5y7+ID1bLC0Xm2er0juwznKS7eUEI4WlUwxk4jUQJHzyNIBpYrgUMprDB7dHW
g9hjz/gPigFXQj+8fnva4MXUrkim2j1spwIDAQABo3EwbzAOBgNVHQ8BAf8EBAMC
A7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBS7w48W
SmQ6hNWW36jCgJg2f9X0KzAfBgNVHSMEGDAWgBSnhYiLnVu0m9mdMuI+/oLzokwg
szANBgkqhkiG9w0BAQsFAAOCAgEAqVmddxo/ARE66I+idk0/CBy2pWOr3aaJQheu
1Tia2MmrQ4PmurKfpPOPbhwDaO5Bu9iNvCdRYfYmM63Sbr9CH8wfa1/x+9xw9VNr
/E07yUBlDz6Y9M+7w06mk2W4PK0wxk/VHhdQ1UaTlpyHpfVv+cJToAIF1MzZNzMY
nVva24JNVMBjWbX/P6tuE3mGhWLjDO0PfxcFyScUS0ZxinOFweUBWG1PRdJgjmMh
VQ2D80VaHAywwD1yr0LQqpq8uUq+SgfjZb0b3YmoGIDFkpOCxIkMQIniz3Lb7dj+
66S1V5DaF0vMCDvzOAslEO9emrDwtaDmjKlrOZ4UC9+F76Br74FztyHSARxzaVF6
PcGQt0WwJ3AIKjy/hYB7Me9+139h7tTGWpv3Nrr5+PVV5ZHEmItIi+shx9jXfuKj
Kl6q9An3uLvT1Z3sOm6nVt6WPwdUNG8jMqZ8vBOUUN4PVuC6ahXM/1Y1C4yIinVa
G/idiMwHoeCFu3ajMmNRHoDxjzeClfw/jBwuh6xpAS+PFljT2O+j2LT5qLB+zsu7
P+wIAMhJhCYm4d6HwYRrLNMijotKHJMboRBgSyGPkGWrRIf7wQskgIG3wS2c4Age
CEUq7FRT4yVpulsLJ+sWDkFnLdOJ5QBGJUgR6MXLkjH9h5BRv78gDg/6l4O3cgH/
weNHon8=
-----END CERTIFICATE-----
`)

func forwarderCrtBytes() ([]byte, error) {
	return _forwarderCrt, nil
}

func forwarderCrt() (*asset, error) {
	bytes, err := forwarderCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.crt", size: 1493, mode: os.FileMode(292), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICWTCCAUECAQAwFDESMBAGA1UEAxMJZm9yd2FyZGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA2FLNjJwGLu9CkOX28/X1zlfv/7YmHYS4/KAVnPIM
+rOgBZtWGkSdx3qAkOWWj/h/cr4gZynSo8qGPvf0KxFdjCP1I/HG9erTFdSI7tdF
n8eTmZPheqfJh6wfW6SG+SNz38AqLhl0GPFNpnjYD5zl7/iAQozolF1G/+l5Jm1H
DhR3l4JgX5KaVZEdbNW5uIadCZdipd94i+1VK4db0w1XP/wfz+c5Tisu8f4LbhCG
iXm4Jzwey9j1k/R5y7+ID1bLC0Xm2er0juwznKS7eUEI4WlUwxk4jUQJHzyNIBpY
rgUMprDB7dHWg9hjz/gPigFXQj+8fnva4MXUrkim2j1spwIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAJPLKYzY7IzUZatvrVvoG3L8h75vhB+E5JeIalp+wHbw9IZJ
o6VYxSK6zkgpsfv5mwwOCmFaajBQ5Pw4SfdPUVZcnmx4iN2PSDb+DrllEw1+D4jz
F54PAVcEo28vfzG9SoZeSa6ZWkxQ26BFLmyVHHioUSK29u/IXgkHSy9oIMG2I75r
JiOCnyVDaW121jwYMpj1R1i4CsJp5U37JoekL3n6yXNSQ7afFtx1a7WJu8KkZgZF
CFhjMSZTlCllZidqgYzlqrH/NhMRtgByVoWM75ARMqdJPWfOc0CwBWt0QADutDy9
JxNrG2gsM7+SX/qHgwnb4aAsaBFHupXXv0OsLZs=
-----END CERTIFICATE REQUEST-----
`)

func forwarderCsrBytes() ([]byte, error) {
	return _forwarderCsr, nil
}

func forwarderCsr() (*asset, error) {
	bytes, err := forwarderCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.csr", size: 891, mode: os.FileMode(292), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2FLNjJwGLu9CkOX28/X1zlfv/7YmHYS4/KAVnPIM+rOgBZtW
GkSdx3qAkOWWj/h/cr4gZynSo8qGPvf0KxFdjCP1I/HG9erTFdSI7tdFn8eTmZPh
eqfJh6wfW6SG+SNz38AqLhl0GPFNpnjYD5zl7/iAQozolF1G/+l5Jm1HDhR3l4Jg
X5KaVZEdbNW5uIadCZdipd94i+1VK4db0w1XP/wfz+c5Tisu8f4LbhCGiXm4Jzwe
y9j1k/R5y7+ID1bLC0Xm2er0juwznKS7eUEI4WlUwxk4jUQJHzyNIBpYrgUMprDB
7dHWg9hjz/gPigFXQj+8fnva4MXUrkim2j1spwIDAQABAoIBACZ+ZZFV2kvTy5aZ
NV6oL/tt7okkUpgCHCDoI7Bv6htah2k4ARRfjWwHwoUGNcqcv6EdcAqriI4Y5dai
rNJVHr5nT6H7zhnIlZNW5J8Ls5oBG6TCiecXoGcCG/pkxpfi1SXFvjvBz8T4e4ba
DiiJFOmk4L328RQlnRLA6wwJehFpAvbC9j8IVGoMpej7utPrH8xcHKjtmyA5z1d7
IVype0gqAq7aGs5LYHAYu5+FedOo+1AD/8GtDNFjXL6oH18ng3MLy7fX1r27LUwx
TWrjuITdTOSHVxDPZkfSqV6YAOotHPiPSo5DcN1O/YheNpSfLo3CnwvinTEvZrG2
LVUD79ECgYEA/i3xmb7ic+cpFzefkHIxjyjgz4h/kobQRrtf2S4Sr2dIg9fu/eER
YrSO7hoBUwnLtFY2SsmQ4XsulRgWGr2JqBfslAHwukajkd3g9V57O6npt+Uo6Zf2
+fbFZQBvp83vxP23bG2texlRmkeohkW4qzxnF2aUCDrzCBKl9FIU+a0CgYEA2d9y
jF4/8gvdM/aRyqCCuEcY+8Hf1NuEPRQ15GCw5j2mmGS+o3faYqoGaVHAla95AJb0
Lx2HHN4of0jp9tco+At36Exf8FCVTundVYhJTg9f9r2e67CJzCKEkKE9NPnxCNd2
Nt2n9FCVNoO02BlDjao8/XWlgVfh0RsGEk15siMCgYEAvC81xZduv1LwuDDFYUM6
b/xa3Sv5D3nib8vAPeH/kX+NT5eqaKqenY6Cl8QHIPyKpZyCm8I6EsaJiXcIvol/
hkUYMchx+ufbqF42dFOcN2MoF6+BJ9kL0KskIBA/mmQ81YLmr09QdmgbY3cUTT0H
aTfSN6AJj0Jdtqdf2NCAmQ0CgYEAxWoRihzwhiq34Zi+28J7D+zkN2KhpWbOuOVy
O6BdShJ8vMM0djxodlQngRDhlwArfRxK39I6li66tTLlRJQK/E6v9J4XpFHwKFQC
CLl36rJFuvZwZJFPGtgAFGj1Y+ZBwEgzRl2sDNVjjsTifZjOvDOQFf2e3Mc7x1Rc
OQNYjM8CgYA1sYcQGrX9DzX/VKKQjJ88V/lc8Fan1Dd/fjQ5kAKJAGTAdmC0r2Et
mJ33hJ3YnUC/Y1OUFJOoqM3oI/4qlf6LymgsjTC9EIv6IMvH9RMx+RukOmGiVfOG
5Pp7wWq9mvHVIGNJF0oQaCWjbo7LHiGUOcc8DJ3x817VoqLIogb3DQ==
-----END RSA PRIVATE KEY-----
`)

func forwarderKeyBytes() ([]byte, error) {
	return _forwarderKey, nil
}

func forwarderKey() (*asset, error) {
	bytes, err := forwarderKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1547750008, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrl = []byte(`-----BEGIN X509 CRL-----
MIIChzBxAgEBMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMTDWxvZ2dyZWdhdG9y
Q0EXDTE5MDExNzE4MzMyNFoXDTQ0MDExNzE4MzMyMlowAKAjMCEwHwYDVR0jBBgw
FoAU70IgI0xPsMO40D5AfP1t9490UTwwDQYJKoZIhvcNAQELBQADggIBAFMcbhyY
GfB7gMb9FV8TSEq1fgKBNE52JOQ2ChQ5jj5N3K3XG7j4/lbD1VVwg/Fk/q3XJVte
S0PHGL+W2I1nfll+/YqcutXu165BbwSsa7Au+M78NAGHe0tq7Fo7nmvcrD4XmIY5
Jk9FUwWBb6S8Ld1J2MqeZtzRwOCc/oMTE1BURAPqO/pK/XnUK/ZV7RlvBWxS34SP
52bBnMlOecWtJlTZncVt8Z3JkH7Nr5lDx27mUNdQzR+Ino5kCbcTAQQmJsjEpOaY
iJN8Ds/b4BOwySAl5jccJvFn8/goybCkCM8otEz5+JM+pGPhSVJYE//mdpIFhS/N
ZdO6AKVh6Rf9A0Xy+KC/TCS1xjw0tglpDxXgAcnfhtBwMBvvKsTtW+ITS8xDtt+8
tc9ZvQiNy4NRyr8HsN8Aqy4DEt0HAh77v/JtZda/9r9xYPmnzliVuM2f9Wy4RReY
/gORpYpHeMMgpwsvjjFV2MGFKvKcE6hYUd7rz6DZDMYHkBvaH7Z8M4HBH+BByPmd
1+sfZas1zSeRGKYsiRHbJJIM85BXt1pNUHiNSqOCTrUhsGJ/AAqJkDf6S7hewqTL
7JK/Iu/9Uff7zONT01yMK9SKvXZLtjYto612VYAjsd0uqY9evm9OCOJpVPS2LLm0
l5+30FLySUTleyGXhzaZepwPN/QUInrjK9Xm
-----END X509 CRL-----
`)

func loggregatorCaCrlBytes() ([]byte, error) {
	return _loggregatorCaCrl, nil
}

func loggregatorCaCrl() (*asset, error) {
	bytes, err := loggregatorCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crl", size: 930, mode: os.FileMode(292), modTime: time.Unix(1547750004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8DCCAtigAwIBAgIBATANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDEw1sb2dn
cmVnYXRvckNBMB4XDTE5MDExNzE4MzMyMloXDTQ0MDExNzE4MzMyMlowGDEWMBQG
A1UEAxMNbG9nZ3JlZ2F0b3JDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
ggIBAMIcHwWWLYp1LX5/70bzXFoyOUNk2UTxVlJocilpt7XVXc4HwgJiyhOe3d6n
MHf83LrnP8HPJNMnDOJ0SDWNMvSlPTtFELs96GeGtfq+kRDAfwPqhw8GIso1te6U
o3IMZpmDU2Iy5JxUKJhJL5ZHN9kkkbE2ipqK/3kAuavk5/ai1iGvvSYJYQqyhpRG
CIRQE8fPOuS4YIkrPCxB9oQuUYObmxKuxFRSXWri24dmzijaV7PkQxA/4wdeBhz6
S/7gMLMOXNQ6PQykd4xcCpytMQMYGExsTl30kwmg09q31znU/Ns413vpMguy+Viy
YXi7urpjPesCNppm5ZrniAVjElQi6GZuds739Z0hg4A5hLXn9vX8tHqcQVljzqJA
rSe0aRVo2MahY4ozN7ZlQKcjYWX62/99broOKBQVGeNiY2kdmiR28aBYrFKgoNXp
jvhrkpEFXPiykG4rbdRmSJY40Qs58gWRDhE9yhQYif7mL725UAXElYTibIkIFfsI
T5JfrCMurDcK21HRke0DKIv+fU8yOT4xX3dtWk5mbd6AOGJhhnLSRURJmzOhEIeW
f02DIb1seknR19XvFiivssme4H//tqxRn/6EeZzKUNRZIeHv0WYPTjtpAIuETsVK
vaUd2TFgbl4TbQFxIIGVb+y0FbSkiAcCMVM532uT2vpiJW7rAgMBAAGjRTBDMA4G
A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBTvQiAj
TE+ww7jQPkB8/W33j3RRPDANBgkqhkiG9w0BAQsFAAOCAgEAesvpqYbwcpnmEq0a
7PYKn6ULTv7muMolkG+qkCZtnt7gD3Dmi6DH1eHDQEdBcHPFCJO8mP6TNlGjLzTo
VFHBy6V/N/aqwohTkvYFNvlmCa/Pp0gJti4iuZo3rNro/p1rl+FowfkTXxJ+feTG
0B6grnM1g45qDerG2GlnrZ2uMMWVHveYVlCDkB7paPbccVMnh5sH2iimvyR7wuX/
UmoD4SFSh9kM778VAw4S8jHZmegYmkRxG1rM64O26ZgebajqRZRqSfBs3OtItymr
91MG5rbgf3JxGFJbrxGJYUUF1WAGRyrA0C9dhUMJgcwV4Y/RtPuSsL7XEPBRNDb3
LcbuwAKXotgAgu08R0qcA228ESsBkMc+U8f2M+Ap+U9cyvCK7FSivLVgMvjBH7Mj
+qwtQdJ0w/jwIF68GI5QE4kKTaPPApGNDXv08Oab7filZQkZKOhoY/Btx3ul0ywy
24EOVtHOptQmn1aVtMiLy/yqf3VxppOaKQq7c2HCiMjXSxqet4fT34x3ch9MFN8G
30w5ECxFeAjvN5e6yey2goNWx+tiwTWpZGXAzHN7v7S1e2ENjpQ7Rh7wlkPHhEcE
fzNmMN89fWT2NYs8bdijR+UiFE6SP+KmXM9UiQkm6sbQIRnIhR5goQsoEaIj5PQJ
Q0SGCX2Crl1LDIBU8wL2edsViqs=
-----END CERTIFICATE-----
`)

func loggregatorCaCrtBytes() ([]byte, error) {
	return _loggregatorCaCrt, nil
}

func loggregatorCaCrt() (*asset, error) {
	bytes, err := loggregatorCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crt", size: 1773, mode: os.FileMode(292), modTime: time.Unix(1547750004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEAwhwfBZYtinUtfn/vRvNcWjI5Q2TZRPFWUmhyKWm3tdVdzgfC
AmLKE57d3qcwd/zcuuc/wc8k0ycM4nRINY0y9KU9O0UQuz3oZ4a1+r6REMB/A+qH
DwYiyjW17pSjcgxmmYNTYjLknFQomEkvlkc32SSRsTaKmor/eQC5q+Tn9qLWIa+9
JglhCrKGlEYIhFATx8865LhgiSs8LEH2hC5Rg5ubEq7EVFJdauLbh2bOKNpXs+RD
ED/jB14GHPpL/uAwsw5c1Do9DKR3jFwKnK0xAxgYTGxOXfSTCaDT2rfXOdT82zjX
e+kyC7L5WLJheLu6umM96wI2mmblmueIBWMSVCLoZm52zvf1nSGDgDmEtef29fy0
epxBWWPOokCtJ7RpFWjYxqFjijM3tmVApyNhZfrb/31uug4oFBUZ42JjaR2aJHbx
oFisUqCg1emO+GuSkQVc+LKQbitt1GZIljjRCznyBZEOET3KFBiJ/uYvvblQBcSV
hOJsiQgV+whPkl+sIy6sNwrbUdGR7QMoi/59TzI5PjFfd21aTmZt3oA4YmGGctJF
REmbM6EQh5Z/TYMhvWx6SdHX1e8WKK+yyZ7gf/+2rFGf/oR5nMpQ1Fkh4e/RZg9O
O2kAi4ROxUq9pR3ZMWBuXhNtAXEggZVv7LQVtKSIBwIxUznfa5Pa+mIlbusCAwEA
AQKCAgEAtiEUqnVCvcs8qJj5tiTZ3neJa0bQ5fNb/26oz1q2WRKeNZbp3rs6yDYk
D6nnvG2x3lzkYcEu2ECnwkNBDZ4y1YHFdjtTe5yW16x6S49LJeC4TMBdgSdMtVa4
IeethHFGQ3wJXPZLsrL0dA8Xa3XfXQsG+LQoUOFi2/JmRHc/fxdCu9DdNTdPqm3g
AHfFvgA0zyIOLFUjnxDGIPCzkUq0iTwTwO/inwu5Q3UgbmdzwLk92TiwBCstpdf+
/GmNrNRGXXt4dlk+twIKedRS0LdgaXrOMcbdsSKuZDZXEb21YDoMFtW6ujUQFBIW
C7cz5cifaAt+KWemPDGX9kSQSB2xL0VKf/JItnfN8aW2Odc8Z85AmwRkYPBAbEQs
GLbQ+IPeBlpktNbGiJv82TV3317CzTdAAD25tkYMy8Boh2xXj8BCOYc4RFbBIG6h
ND6yZ/oNNp2r8PR8EqQsuJob18euFmixrkpeRHhd5fF+b4di6DLtVv84qTRyRChm
mSNj+FubMa1cDo/p9rQ6C/aGmkX5wztZwPc4XJyaK8XGPBFOEOaEYiHK3GGS1c3s
OHZoL0kZhSdELUNmR3jpPwiKTvHY68N2rKf1SLEmKgwY+BBomu0WNR2PoI5wMAIW
buiZDA9oPt1wXY2LrlHQ6yN6UOKXlLRF83uoL1ANx5UyPIGzPyECggEBAO8DF0vn
3tSlEskgE5NElbz8qRnbYukzUVOHV51ViNOnsTcFTqmYOrN5T3x8JnsZXu4JyBw/
UmrBEMBnx0t+haxErXOPodazvz/B7lwKYk5vJoHKUfZt61IDyvClFlidNWCGCj3c
+H+4fCYwgAJbW+fK/CpdNJYGWo5zFR7seZyeX4HrENWA3u/joAOJRjpGsbmcm6lT
tK5Zr2fZDaB5e1YWT2hKGLX9KDBLF7D2SvWPAnPIqzw3mpX0dqWywzNCg/Ek9ALM
EXRsbmEdVOkDtAe2Zg+DEijP37SvP1qsKcLWivJ5ZagpLqPjLvmUEuBVkKxwH/HY
KAXT/GJROtzJ/YcCggEBAM/oBLHZ2tZPt+h7zj56nQ0VrABgI6/JBWWOByqWYw70
rAx6bjYxqOmubVxdgL8Nk703f9gtI90B7KUgYj47UJ4jP/yymC6E07mWvKf8Bi8I
74oSyCvnEKlbh4H586nB6An69wdFN8FW5FWltdG312DCOkrOJth3VMgXfjUznwzP
VBmr965mD7TVFXW2Jlt38CnGQ9dBtzwzl9FC5Oz1f0Nvb6x4gU1hTHc1FSmXcNIt
rFSgjGKN6y+hYztNgvshKrc/58YAkaFERXcgdpb3LohMamj8HGLoWwDWhcI1EM96
J/rB83tc4tk7iXGwPH1nr1oMpX75BWaltI5EyGFfPH0CggEBANPeG5KPsbkxsttS
ccfDrjBej895583sTZULjiDLp4RnS/IH5Fj1tmNNj6Y7ryjDrqC3TwmrH/W9uomz
9Lf5KakxH8gmdEGMCGYOFKrGEaqRYMMAg3M8sLJ85jI3RP28LYqohv+blzQwZuy7
ZV2xemCYULuE745lh3RqkzhcStkIkoTpyHxZxkVDs54u22/hJr3wExQgPTOoEJKv
lyK/TRNcp3s843a/OBbHGfMmAAB4iqX0JcY1S/TNRTdQpTQVLDxgk2S/XGGllJrF
k3UScU284++wMjK3Qgg6qKBJqKMr5vNVpUVRbCSeyA84sRrm/l287rRE9gVkin7k
npcE/pUCggEBAIMdzRAo11U/EznAEpLemvsshrv55aevvAKO7sAR9cjxzytTbvwo
l2FASuHsagyTUHANd0frN+nik86TvMGIgNAqZOlF7KmxxSEPCk1aqL+y//Zw3+Ko
J57XBX+YFe4iRuc8adwg8Aezd+73wdHQAjmYZFDW8DKmF0bVYhfFRXI7sss548sN
vKwLkiwZQtl+q2x9CD3RyPBjjURAzsUOEkOCHMiFeu5FBYdMZ9tCEbnLaho44jAp
VoBEZKN6v7cG9Lx6xf3eT/mHZ9O4GnIc0zDMGHO7Q1+xL+s4X0TaWI6weFQxSw+q
xbnATW7weUWRRUoiHaEVBS32JQdwI3sdJ7UCggEAbPys38uS477r2KgUkI7q5d9h
37D4DonpNCMUu7llJW2Jkm/oLwBNZoY1iawCok6uq8VieowghYihWP18+GPWnnEa
HTv81bvNxuWLDUdGsNS4SotVZ9yFjxBGoWffHnLgJj9Mjq1lReM2f8KyuZP6+B6o
zZ82/1L8Di2R9CfH9mJT8Vbupi0qSjkuqdeMw/0P/qlwaIqAQGrgxQV/J8A9Ld9t
FYxx8eAaahWKFt99VedNj0ukotWLAhJufwK5iZvKq+2LpYqwS80PtcCVqbwh1bQI
ht4CNUMkv1P86qv7AbLV+BknMHk8Qq++O9lfLmIil+09xrffJ+IHZU9B4mD7yA==
-----END RSA PRIVATE KEY-----
`)

func loggregatorCaKeyBytes() ([]byte, error) {
	return _loggregatorCaKey, nil
}

func loggregatorCaKey() (*asset, error) {
	bytes, err := loggregatorCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.key", size: 3247, mode: os.FileMode(288), modTime: time.Unix(1547750004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJDCCAgygAwIBAgIQW0UgjMgtxQlAkXwxxgXrPzANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE5MDExNzE4MzMyNFoXDTQ0MDEx
NzE4MzMyMlowETEPMA0GA1UEAxMGbWV0cm9uMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAynjzMNzkEbj4DNALaaOhAgFk31oF/3oiZlybj90YxZChZcOW
Pgn/OkS8S1iIru5uC+voFCwn9IZ/1s6jeDnPsSaVcdt/gbuZyGveQwLFKIskQjQg
ddN4wdAXyHu6QcaZ9Ih9xB/BSTJ7DNbm+JnZR62Zoeje/ROk83zlwxHombHZW3I5
eR9DU5mgCvHXXKkXmuGHIfO4MSUS6GG2QA6RPV3sQOJzzwjIXyepFkc7ZibdfX6C
Oxobe+L2wwy4BzE5HHmtl8s9PHxShqmrXRtRTxQ+n6UyIOfdrsaISqzdefv3nJTH
qNWXmwBbObY276w6koa/Baowax3VZ+I69bXq7QIDAQABo3EwbzAOBgNVHQ8BAf8E
BAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTB
92CFvtmF+WzNuvZl71X8524D7zAfBgNVHSMEGDAWgBTvQiAjTE+ww7jQPkB8/W33
j3RRPDANBgkqhkiG9w0BAQsFAAOCAgEAPTMyGrV1vTMsD3Qaybj5ghy3Cpr+fHfe
B8d1+bWq8D3k5F5HPt1n+zY/K9Yd3Y299j9Tfm7sVOQzT6ye2rNF8/N1GK2t/Slf
FpL/HTzxCN39S41IAhp2DhdACWcoQpjCGK4T8DLtpda1BpIaekRBr8zhXDBXGmh4
/5rNcxtxQAm0VwgLTiyHm2YoNhhduyaWuT5ijQBDkAwYa2e4v0JgoGVsa27eFktr
KdaWInsF2ca37XHJzVSZ0T7RR1Z9sOxrx2/XmHOkY47DiW0axImqUw9kiPn5/hbK
OtpzkbfKK/buIbfwXjcefg8qMFzxe49+mDxUB+b/KXi9sVR82kmX6q93KqxUqdIU
ikyra4wCoJq2z6sP/gErn1n3dKqT/0xwJGT4GIv+5dGuDncZnxEqXjScmkao5cXP
XJYS6f289AVyFxhVHgLhjDARNPCU3h6nxiRbbQCfKtBDL9/I4ZYZHE/tsmsfXSjd
7wHvJfGmvr1wHE7L1rBAim+wbOX0HKp4KJ/WJ8Ez2s1YUY2gAiEqasBIUIoXeKPs
oBmjFwKR8J50sJmcfA24FsZb/uDtmJTpxBK+ZTbDChMR/yqZgrZQZKUJtqW0TQvs
Ood7I7xaElJK+yWLXB7jV2NQ3pFs84E2+wddDih5lbf7ViTUbE7BB16N1YnKee+Q
PSdYt1hTn78=
-----END CERTIFICATE-----
`)

func metronCrtBytes() ([]byte, error) {
	return _metronCrt, nil
}

func metronCrt() (*asset, error) {
	bytes, err := metronCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGbWV0cm9uMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAynjzMNzkEbj4DNALaaOhAgFk31oF/3oiZlybj90YxZCh
ZcOWPgn/OkS8S1iIru5uC+voFCwn9IZ/1s6jeDnPsSaVcdt/gbuZyGveQwLFKIsk
QjQgddN4wdAXyHu6QcaZ9Ih9xB/BSTJ7DNbm+JnZR62Zoeje/ROk83zlwxHombHZ
W3I5eR9DU5mgCvHXXKkXmuGHIfO4MSUS6GG2QA6RPV3sQOJzzwjIXyepFkc7Zibd
fX6COxobe+L2wwy4BzE5HHmtl8s9PHxShqmrXRtRTxQ+n6UyIOfdrsaISqzdefv3
nJTHqNWXmwBbObY276w6koa/Baowax3VZ+I69bXq7QIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAGH1g90M7QYh4rbGHnDiogn/uL3u1u7yA5tkpYjG15QgA9fhK1Dk
YAu0zUJx0i6dW1xrHoIDJgRBa8zrrjsxxk2d9evhLzBgPjO4omQiAtqKUH/7V6fU
5kQ1DkePTKZMd7pcs5EEDxLZR3F5f00qFq/Hv8VDbtApTwJAiWgTnIfUr40f/n2Z
BMwKkUnVvqSr5372pR/MbfFJui3z1ufy1NHRQ5uCXn+/DfUsGvX1OOZ8HaBIExQP
rRAU3Z0SYVJhDHR+PvDtVVjXtCFQ6Hqcc+eugbRdnsNcdhIlxRQknD2CcnY2PYzr
AeibDgLQ/JBth6toNmk56/HU0cdNKzlD57Y=
-----END CERTIFICATE REQUEST-----
`)

func metronCsrBytes() ([]byte, error) {
	return _metronCsr, nil
}

func metronCsr() (*asset, error) {
	bytes, err := metronCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1547750004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAynjzMNzkEbj4DNALaaOhAgFk31oF/3oiZlybj90YxZChZcOW
Pgn/OkS8S1iIru5uC+voFCwn9IZ/1s6jeDnPsSaVcdt/gbuZyGveQwLFKIskQjQg
ddN4wdAXyHu6QcaZ9Ih9xB/BSTJ7DNbm+JnZR62Zoeje/ROk83zlwxHombHZW3I5
eR9DU5mgCvHXXKkXmuGHIfO4MSUS6GG2QA6RPV3sQOJzzwjIXyepFkc7ZibdfX6C
Oxobe+L2wwy4BzE5HHmtl8s9PHxShqmrXRtRTxQ+n6UyIOfdrsaISqzdefv3nJTH
qNWXmwBbObY276w6koa/Baowax3VZ+I69bXq7QIDAQABAoIBAEksXw+ItTAmfhb7
VTSPe0/jOxZxTXugIzCFRX8/s4UrGPlTL0gqir//OWGtlHBMIR9T2aL4tlPsC+WQ
9okrs4DdZeMpJbK4HwLM4R2ssZ5OcwMuHZEXpSu+TeoZtR2ybc9vSKyJoWwXv1rL
i9vKljkOZ1iZdYVXBSUuPUc7gKmSdPU5zkM8qUfBtky+0IWSLzMhiNXrXdq9BTb3
weCQIR8IXAMLVWIbzHAEsQnj8WFJYwj/7tJRSphXodPqGaBXRgAxFt4zKOUvPCyf
iE84lKfwpHM7MI4WNybu+Y8NITByPcnhLs5S9Kx9tfs6rpAif+DEmTyM4kPAS/k+
kT8bRm0CgYEA0/jXnUYxQnsyh1zBUYFNLhsHD46a/6ZJSgZZkKWNOFfgqng6hKg+
vJiRxJ+u4TGREFojnUbF3iYCRh0Bqo6DnXmdbS8bSR7JvEF7Wv20OT7jCuGUEB0m
sSyW+AU3ZSPqKzVu1HaW1wnoGH1KUQaLA1IOKaoDEH6QZBPeoIqiRQcCgYEA9Ib8
7hg+iDTyB1PqXKEEjJuGrgNitdxbL3H4JCFPJSH1Mt/edWZECTSM0s6AR2Khy5lf
rHSdQIyvbwjxJkhzmw7sTTbDLlDzQufUsLu9vIq0IeYgkdu7q3P+KcueIQ/aSIbZ
l1RAV1G96DcaFzBQZRlGLucBgfNVjgTbfMjpJ2sCgYEAogbRUV+pIacoDX4iKxoK
E9cHA6Y+5nGGDfZimgVhuBK8IbH7ERHFusVojwJ8W5hWyUgNdxf1AYTOMifT8To0
crfWVPIwCilljOgE0Z2iGCvwwo2BbvvJap6p23WpTT8xrMuQJwlq7X6eEbIbj2nP
8r7TIpfY9c+4sTba8p5lwRsCgYEAgmCC9XQJy1fngA63E8JqiYnXKmr1s5+VItvy
gVkdOOA9O23vz8rCFeJl/3RJI0asm8DgKTRYL/WTCHHNGithMFipl5XORaC1w4OW
fNDtHl0aJETuMrbk/kqvRpuhaWFpcmgsFiq+z4/u4KSYjaqeAvmR2SokPKSAhmOC
n6sD3ZcCgYAdck3GLApsrz6q1N+lmTv6xLC2m0S9kPFa3vK3vIzEUvfyCgdfim1j
eDqAgo0rQJrzOZoSZ50Gi2TbgkHFokvLjLthAvzvRozeQifBzpZCuOOM2Vbv+J9h
QHMkBjOXnkmupWgd5bSmEWgi5TBbOzfUob5+Lf73z94QHRNbRZ9YWg==
-----END RSA PRIVATE KEY-----
`)

func metronKeyBytes() ([]byte, error) {
	return _metronKey, nil
}

func metronKey() (*asset, error) {
	bytes, err := metronKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1547750004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEKjCCAhKgAwIBAgIQYz0BtyYdXQzavCe8+b5QfDANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE5MDExNzE4MzMyNVoXDTQ0MDEx
NzE4MzMyMlowFzEVMBMGA1UEAxMMcHJvbS1zY3JhcGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAvI89Zy4Q6B9stPaRgWoSltO6Z0WiY8u5kZBV6swC
DM5nP+7fz0Y2b09QKs+1tKRHcIebCVodABmxpRplc6fw+Qe1Z18Dl8+hEtkZHHMQ
s6Z2706pRETFG6aoH6axzrpcWK3PkovlD3gl5Ie4AXdFe7NgmtG6Pu9fj7/dlE3Y
mv5oI4K/FFn77Z6f1uzLE+GdguqZpkXzQ6yxGBvKyyPo9R6DIE7BdqcC27urd2Xd
hzfRL0W7dm1QoiiPFkPHNnYqZmtjEpeD7OdrGWue671U011feMaHLbHfHjgXlZaR
JV7Rr2ORgYk2Qe9v6J7JWMxJDDiN31yplN5QRldRPuB9YwIDAQABo3EwbzAOBgNV
HQ8BAf8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1Ud
DgQWBBS6zexOUMpaJWF8Xow/ciZtKAX1mjAfBgNVHSMEGDAWgBTvQiAjTE+ww7jQ
PkB8/W33j3RRPDANBgkqhkiG9w0BAQsFAAOCAgEAJAXcqFi94KT1uI7YkJDDXSaA
Eo3dYlMjkWEwDUeR46dKrLcVWN2DxwL7s4rmG+d4Mc6LPAUp+HGVeGxqDvhcBC+8
EJLHPvhakFj5czja/CyKQH5jf/bK0D33CFrRJsGiNAX9p0DrmDSI0HA1NXLqXSOL
Kbb95TmGuJzKJ0TY8+P5ZoSOvBke1emP7UdMwwpy5/ekkHhSW8cnOmS0zq36VYL0
alT4qaKGQVX5WS+RgBFooDDbEZx0xCeubWyZqcCAEEiBgT3Hu57YdplyUUdVEKrx
KgRy32nqUwnSeUydNXdRCe1QOLqmxYRRvElWr3GYI8L/tMrzQscr6zlIc6wIa3gg
pQHUXGJwTfZ4USy6jMhDB4onoSVqTLdtvTHTIL8URwPehYgDYcALylNrlgPYD3uN
XnAxr084kGfNJX2umsLFrgVs5KIIKdnL78JNHUkNtMEbQ63hQpZtVfymwFyscTRC
ZtOPuOeVGSdoMgp6eV2WbJTR1wqf/1n+aRUPKWDaemeDdu14lvm0wC1xwKEzsHUP
ylp8vf+2BEPDrPVN52QFSkZTsZldkRn/KND02DAFIR8EKsv/GsuXNL3WKbB1+9kW
LZfKu0MwXqfNNl6RmOZqr56Z73qOEdxSiOx2E32H0TkF4YLiqPgQ4sBrrChDWi/T
YyFNc+aOvRcW3tFTn8A=
-----END CERTIFICATE-----
`)

func promScraperCrtBytes() ([]byte, error) {
	return _promScraperCrt, nil
}

func promScraperCrt() (*asset, error) {
	bytes, err := promScraperCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.crt", size: 1505, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAxMMcHJvbS1zY3JhcGVyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvI89Zy4Q6B9stPaRgWoSltO6Z0WiY8u5kZBV
6swCDM5nP+7fz0Y2b09QKs+1tKRHcIebCVodABmxpRplc6fw+Qe1Z18Dl8+hEtkZ
HHMQs6Z2706pRETFG6aoH6axzrpcWK3PkovlD3gl5Ie4AXdFe7NgmtG6Pu9fj7/d
lE3Ymv5oI4K/FFn77Z6f1uzLE+GdguqZpkXzQ6yxGBvKyyPo9R6DIE7BdqcC27ur
d2XdhzfRL0W7dm1QoiiPFkPHNnYqZmtjEpeD7OdrGWue671U011feMaHLbHfHjgX
lZaRJV7Rr2ORgYk2Qe9v6J7JWMxJDDiN31yplN5QRldRPuB9YwIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBALCLuOugqU9NsjbtEtmzgZynAuetKUpDS501yJpJpu5j
kYlEKtj/143URhZ7j4KWLEdZCOJx5xiXtgSY9+PBuy3hhJCffLRDuAO0bGmju0+I
t+X33a1xh73aFNNbGfkmVXJbR1LMzjUUGFFXq+xkEvLQ8im4dGzK9dTbwhi4BElj
OmYH0TvwcVSfdxX7OjTvFnN9ePizHRMWPGk42ks+HemqBa/qW8OMEFzlBfDxcYxb
SzDtn29VK7Efz8cmCokjfBovl94rzHvCbTR9AC+UMYdv9X+aMByuhZ8Iapqnl9a1
s0nY5MNu0lYpfabmJA7xbzwntR0x6lRalWEE+F6aoJ4=
-----END CERTIFICATE REQUEST-----
`)

func promScraperCsrBytes() ([]byte, error) {
	return _promScraperCsr, nil
}

func promScraperCsr() (*asset, error) {
	bytes, err := promScraperCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAvI89Zy4Q6B9stPaRgWoSltO6Z0WiY8u5kZBV6swCDM5nP+7f
z0Y2b09QKs+1tKRHcIebCVodABmxpRplc6fw+Qe1Z18Dl8+hEtkZHHMQs6Z2706p
RETFG6aoH6axzrpcWK3PkovlD3gl5Ie4AXdFe7NgmtG6Pu9fj7/dlE3Ymv5oI4K/
FFn77Z6f1uzLE+GdguqZpkXzQ6yxGBvKyyPo9R6DIE7BdqcC27urd2XdhzfRL0W7
dm1QoiiPFkPHNnYqZmtjEpeD7OdrGWue671U011feMaHLbHfHjgXlZaRJV7Rr2OR
gYk2Qe9v6J7JWMxJDDiN31yplN5QRldRPuB9YwIDAQABAoIBAQCnRvvWOUvOYXJy
5/sVsCBlpdfMHj5+AhHSTRWrguieq811Lllm7IcGIHqiQDqW0tZ9wg+MMGFh4Wlz
awNtoyNoCaqo1eW+G/htXCOm1X2PorIIguQvKEMk0Kh9y8gZ+cJK+YcYHvtKye/z
2WMoCcOehffB4SU1B+7i+/d6xcTPWjGxMgr/Xxkll4mHYvMawONl34620M62obf/
wt2MteG5Z/EVfs1EcjSo3JdJlP5HagR1suABCxZe1PRXMpj047lfvbjibLUVGDqS
2zZtHSDXbPKTBZ8C8NCo3fhNcC9aHTP4mx0A5H5eIuFZXTO1a4Fhmp07LPZKBdf5
eEsk8gIBAoGBAMDs05KuSENOWFoBbwTLwZaqX9UFuHkNKmmaa1ICdf8Hyxih4lo8
xgNIkCdnd31n1MUhv/vMviGc2Txhgb0REfzB+4qPzOuDj8w5UqEGfusg8DmWJspf
Y+H+ffnoY+s+xnJqHuvOJWp+wP5MMhXFkmUiRKP1D3HdyB5Yz1aXxMHBAoGBAPo1
B6QWjnOl4FElYVY0c6jnyBe/mxpVAxqyCgbC7CnvQYK0dafDHnqxBJdbK9Of57lK
zMFjpIxXflW8G2xWwbEI/dYUZ+VseLdcauKPJ7OY5dI1J/HjUTszfpR5/uYJM55Z
5YgljGn7pGFjgcLwfRZ+F8c6YHG31+zsqr5pegAjAoGBAIId+GBAjVpft7UUrHTW
m71rMXEyB4YVPBq3XFSWdlDIR9FYNZrYzFAgm6EH5o48/kLqjVpdb4qqB9XyiZcj
sTcA+g8tB298bvq1WqZiBC2/LGYagBUTmwEsLHjlpKZf02YNbsdpZNDbpnyclVcb
xq3RG+xc9sq8YyEcktJ7T+fBAoGAThy4IfYYyuoCOdMdrDf708NoqGFdHr9jlLX4
g1vfNshG/3MvOAymO0+AS3BfIlZNlX9QpR9ig53dBw8O0KfVGFviQy9jsDBJD5V+
mPRwRJV7SkDmE5IQDhdpcRkVBuPghZMzIWn3iC7ThsP2AtHpe1gqPDxxV485jfHk
7EUpnVkCgYEAkoiHpQUVMhgRu61fZgm/9kzsOnqHSjwkNlrIuwzgSa4/8HTTSLfi
7cRfjVPNK8PMx5CrUf1kJS/FXN9ry5w0padVXBPIWnCviZHjhJv6QNqmdnxDRfQC
V0iKCvNnk3YCptqgWljpkExSDDrTi4g29N9fTXzNB9paNNgVLDBMkqM=
-----END RSA PRIVATE KEY-----
`)

func promScraperKeyBytes() ([]byte, error) {
	return _promScraperKey, nil
}

func promScraperKey() (*asset, error) {
	bytes, err := promScraperKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJDCCAgygAwIBAgIQY6NkKEPmcjBRjfwXhtJ1ZTANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE5MDExNzE4MzMyNVoXDTQ0MDEx
NzE4MzMyMVowETEPMA0GA1UEAxMGcm91dGVyMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA4Wpz72AthDsmywA8biXeKs6yOewrFU77MTT2SlPmrDBBu49/
QUnbm5eJ4N+PlnHyaxBaoDFH7lopi0mkgmBvG2BN9lzvlcQpUv67Z4fg9pqMY1Jo
mEqhNI89rBc/E6gvO3egj0QFSOvz8dctkIc9vd/eH7qdm2TDOaZru+d+qwMi9cjJ
5kNLf1gyrrGTymIk1aLDhnlTWFdEO15KUHaBuUV6bFubmWpaJKlckaVNufX5wSSa
7Rc8iAlQqdE+SdHQ/JkPNdqeXUCxPeHr/9El/DfxFqbWGtuZjnWteS5ZY6PwgYag
sYGeJKyB3vyq3ziQPo9HzxQAVMczpvEjh2o2BQIDAQABo3EwbzAOBgNVHQ8BAf8E
BAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTd
/tn/8fRLhu8GFL1R8JA+eE1ciTAfBgNVHSMEGDAWgBTvQiAjTE+ww7jQPkB8/W33
j3RRPDANBgkqhkiG9w0BAQsFAAOCAgEAvE/moD1Kcu4noIlQbYqNXbpHxNfJxFEL
Qh0W9Kej0GkVRUls3bTm09vq7Hk8n1rxmFCPeeYsRAEFhoq/cB3cY7/1Kq8yn+T1
nIz8emT6YADSD51dxtWjwi8ClASXx6yeijFUrDVBIOI/ziPKNKmVn18BC5xbWlcI
jPbIcAOIbqQxb8olXeaPDoDd9g2c1ctj4doDYRgpsFNv+LM91sTc2VAEapL4sB/e
4gJtshA9VbmkAj2mHfVe0KWo3CblmQgkZ3rvvKCk3FXuX2KkqYdEYYCcLTaP5W67
UbKF/5Gao/fc/BhIVGLkz5lGMgG7vn6beKxyodFaIozVFfTdh47E/OUK4fp9TqZ/
DneYPbtyBPyGIJ+3zcy1/RZgJ9ndkKUvp2DjL21O8jvL9tG8MmlNzZP1udmPUCGr
bnedLgk6ICVgrLbiohIJiSlbnVvZUdYfq96ZSNXBhodJY7OhVQ2di/4exfmkoNJg
XAJIe2GUBZQflmWzdRzB/HFbL4gVc+tJXKSE0A6o74psu5niuqDQ4p/89cndI8hD
p77WOyXn9Dh8b0B4gUD5a6baqbQCb+gawrydzfAPIsrhGQVcN3Hgqx2LX8lKif1J
vrfUpEIy1ztNd2l8mnDnb8BMFZwn2ELQEL32TdJkJxM8hTTiguHDO3VSddMvejME
+/+gbk4d+Ho=
-----END CERTIFICATE-----
`)

func routerCrtBytes() ([]byte, error) {
	return _routerCrt, nil
}

func routerCrt() (*asset, error) {
	bytes, err := routerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGcm91dGVyMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA4Wpz72AthDsmywA8biXeKs6yOewrFU77MTT2SlPmrDBB
u49/QUnbm5eJ4N+PlnHyaxBaoDFH7lopi0mkgmBvG2BN9lzvlcQpUv67Z4fg9pqM
Y1JomEqhNI89rBc/E6gvO3egj0QFSOvz8dctkIc9vd/eH7qdm2TDOaZru+d+qwMi
9cjJ5kNLf1gyrrGTymIk1aLDhnlTWFdEO15KUHaBuUV6bFubmWpaJKlckaVNufX5
wSSa7Rc8iAlQqdE+SdHQ/JkPNdqeXUCxPeHr/9El/DfxFqbWGtuZjnWteS5ZY6Pw
gYagsYGeJKyB3vyq3ziQPo9HzxQAVMczpvEjh2o2BQIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAJZozHLGjwz1TJ66IewNduq4qWEeSI9qWv0psQFcR+THxGEqxddG
guvnNIqVl4SMOc6cW7jZ59Lb1OEKwm+t8IG8CX37CgdiCDnDsQ6o5k9ZRCsNFMea
r2ydvpyNgAV/ttKNb56Tdh9DzoEG9bqJQrqrfLvC3LqWwNBUZHIhwe7BQ6/3m2GF
Ehex2OvvziJRKKVP8UTiTgt8XWDA0kpY5lRjihdswanahi9q8vyKOfGH3IT3cHQX
SRjGY7KBQ2kvDGzLFuqOUk+LfaNxhAF4b2rtawyFXWVqwS06WiGPIkmg3MtBoyRK
YzSL6KOqH6dg1CVNIMItG/b/oJLrOEd27y4=
-----END CERTIFICATE REQUEST-----
`)

func routerCsrBytes() ([]byte, error) {
	return _routerCsr, nil
}

func routerCsr() (*asset, error) {
	bytes, err := routerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEA4Wpz72AthDsmywA8biXeKs6yOewrFU77MTT2SlPmrDBBu49/
QUnbm5eJ4N+PlnHyaxBaoDFH7lopi0mkgmBvG2BN9lzvlcQpUv67Z4fg9pqMY1Jo
mEqhNI89rBc/E6gvO3egj0QFSOvz8dctkIc9vd/eH7qdm2TDOaZru+d+qwMi9cjJ
5kNLf1gyrrGTymIk1aLDhnlTWFdEO15KUHaBuUV6bFubmWpaJKlckaVNufX5wSSa
7Rc8iAlQqdE+SdHQ/JkPNdqeXUCxPeHr/9El/DfxFqbWGtuZjnWteS5ZY6PwgYag
sYGeJKyB3vyq3ziQPo9HzxQAVMczpvEjh2o2BQIDAQABAoIBAFRppuy3WZQxCn/u
oLKm36GsMbXbKO8b2pk8uhZvgOxuTc9NF1x9qg2EHA/n6D9wgFVzlFx01/j8Lp6I
f2CLeFAKKmfduaKeCNOZrNhCXA49JeFz1NNi7yddlLzDH83ep4FfdPLxiAEcywd/
iwKagpZ+JRJAshClFS6bkbCWKisjl58RVnXfg8FT9A+uz1nPvWbzpqVTmIlFImmg
HDd5SCGgfEH3GEourFB1zlX9mYlqLE+teeQSK7UrRPoUxTpZ3nmXj/AZiYtSAojt
I74IlXRRRwKm9uq+29a3THvzB7XRu510Vl8y5eVU/XDbfADbQ5/DyD5567IUMQ0h
nndWkQECgYEA7QhWqqr+16aEm+0XFIY9YF5hQyLEk8ObTTfeD8L5MYvvfMVfGqVu
HtTkEb2SuSclEX4Hxka94CXdc9xBdrkKLK66bEov/2O0CSzbVqiaVVrjRv5WLiF4
t3Lxd8mQlRDcs7swaZsvsOdvCcNJDdKKevjpkHq75s9phnrikObNYaUCgYEA83Qk
ml5Q7pdihayGCpkqo08Ab8CKUOs7elqoXoYBVVIRWvwsZpHm7Ru33p5KXu0cU7Q6
yxQqwc0vKD9YwJX75JtqADLv7c3ZCNYimCUUMGYtw3F6+BvfshZPVRdpJ+51MTm/
N2erWf3PTwg6P8Vmyr3XM3+hqHKnWZWXftxklOECgYBqhl3Us6Z2KkrcfI/r1GyO
+7uAXYa01arc6CevM7OkNbx6eYVFR2WXC5w38NeYyGPbWaWK0U4SB1Jf+HOfNIfD
Dv+PHUQ25YsKuJMWfg1mIMOVq0X102saHtkwOXD13S8iwxR90ZV8TnZTj+UsBhvg
Ki9llBMQJtTI8D8UWfWhVQKBgG8D7lEKY0N5eu7T7kfU8pGHy/4pwakGq5eu0YpQ
9zit9MYVqjWXoMNM2XrFmcpRu5Ib5JeIebroUvG6eUFQ442qpRq0H57EOI0EAMB6
YAt1/LZcACQ1qbsu2zxFMamI3p305FJijsu5ppg2e0FrReV7zi9oqxICPnfmdC/g
VmlhAoGATO8JM/BET6D9OYDWiP3hsP4N5pawbXa+hNui28gT3KpNmS5Z/eG7GPrl
+6ONQIJmOZA8BfHhxOBlhTLUsArkL4EyAPlG4KhVd9esbc3eyVB4fdEtfew42xDe
3/vmbCADqveawCFXnTvLQ+4PfQZrBiG4ypuajZOT1O5BUkakUjc=
-----END RSA PRIVATE KEY-----
`)

func routerKeyBytes() ([]byte, error) {
	return _routerKey, nil
}

func routerKey() (*asset, error) {
	bytes, err := routerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1547750005, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIELDCCAhSgAwIBAgIRAPEn3B+aC6TBU+3kvMAR+nMwDQYJKoZIhvcNAQELBQAw
GTEXMBUGA1UEAxMOYmluZGluZ0NhY2hlQ0EwHhcNMTkwMTE3MTgzMzM4WhcNNDQw
MTE3MTgzMzI4WjAXMRUwEwYDVQQDEwxzeXNsb2ctYWdlbnQwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDX0tcjBPGIKl+pRGUcS+B+eDowuSyS1ml9twW8
QhB8zNS/DgeDj7Li9iaClrrKkxDTGmzr/391DhFooBY74QqzY/IkBU8OORa6rYiS
A3EtbQUqf20FSkpTj+QH1AhyyRFjK2GVVnULcEOfQO4tsM3cfEBn96ZOREZvZCdq
H3yVwPLm7qIcdTA8jq1dROD7T5ben9T1JpXadoLKtQj0e+jCU8vu25hlIBMOatij
6pkYiwV/sxo7HR5NTY/gAUWkFi50DHN9hVOIrDT3LsBgqMV5wvodeYbCeSylD4ST
PQckU9L+Tt4/1OdlB6y2B00VaS+6rirIeFhB2EJpU5NQpeE/AgMBAAGjcTBvMA4G
A1UdDwEB/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYD
VR0OBBYEFLoKBfX20eHNlo+TP9OMLvDaBfNZMB8GA1UdIwQYMBaAFGq1Jsz+9ltL
UARQNR5aah5yYxBFMA0GCSqGSIb3DQEBCwUAA4ICAQAm90KrVViNCIE0UlDcfz8I
QVzzwZ2fXpc63MdKvNj+jiFEYWReHjc8fijADKzi5AIN/OBtUYFTVaaG2Ka95tTv
oWvpHCrJ5Uy3bLDtunR7hp0v9FyBsLm7JquSSpgNoVJOjaqtBi7AWzAzr+ehaDEj
zCUveY5tPEO6TRo1QRSNiASMFMzZ+aPVnFQ5kxtf6C+tKh/tPmhZbayOIlLEKmDL
7O1Q10HjJDvgyfMZIyJX8XeA4/mSlS3xgyM3nVUp4a7XcrB5c0BB7Paxzpugt9Mq
dioZOUReqjaijFZOaFaw3pwqoYyBol/CQWSXRbXRiLX7wx+mh4F7ZxwrOOtBkwQM
SQfjVM8FtRRUIJZm8bl9BhPsFo7Vk3iK3nbmXZJMCO7mlrULlm/ED/Fqa9F0Wspp
IWfQkfjHdNyIX+3wb5Fk6EYl/YB06kW8RsAqCpLAmSG4c15YbVn2UhIOhCIRBCkz
DWLl5icJCUgVAW82jdXBh9j1d6u57LATCRb/K6NtkePghpDYyu7SxZ+rJIbwa0dO
0kW7CZ2+N6SxOq8ffZ7GPGy9KBIXT290BiyNo9zk+lW6JJNFRPzAjjocNMn7mG7h
g4xirzV7J2/obBrZSxbhcVazyMOqmIYUfQX/sXEh0AsOesmvZFW/EKTlgE/elZnH
p8oSoxW2/Y1e4bdTT0C12w==
-----END CERTIFICATE-----
`)

func syslogAgentCrtBytes() ([]byte, error) {
	return _syslogAgentCrt, nil
}

func syslogAgentCrt() (*asset, error) {
	bytes, err := syslogAgentCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.crt", size: 1509, mode: os.FileMode(292), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAxMMc3lzbG9nLWFnZW50MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA19LXIwTxiCpfqURlHEvgfng6MLksktZpfbcF
vEIQfMzUvw4Hg4+y4vYmgpa6ypMQ0xps6/9/dQ4RaKAWO+EKs2PyJAVPDjkWuq2I
kgNxLW0FKn9tBUpKU4/kB9QIcskRYythlVZ1C3BDn0DuLbDN3HxAZ/emTkRGb2Qn
ah98lcDy5u6iHHUwPI6tXUTg+0+W3p/U9SaV2naCyrUI9HvowlPL7tuYZSATDmrY
o+qZGIsFf7MaOx0eTU2P4AFFpBYudAxzfYVTiKw09y7AYKjFecL6HXmGwnkspQ+E
kz0HJFPS/k7eP9TnZQestgdNFWkvuq4qyHhYQdhCaVOTUKXhPwIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBAH+JnDximaCaEIDOC+3jvqdGwWbpwD3SIDrIKew7NLDT
uFz6SfCqcBVBv+E1FGmSRLl1srIbLEG45rUigtMzwpGLbWfbm1cchZBQ3fr8v2qP
hK7Lo/GDaJmidQX6WgrM/S0uduyS/ZKdoDhuVVf7L92JynYoU6gFt0g9R+6DwpXJ
WyWG2mr9eEaUPQ03Yl+4BzoCaUMG3kQe4zR6amCsXSN7gtj3+22EC5XdS47G9PtM
7CsiqybWa7lWysDFQ9w2KooMIH5JDlXMhyZmwjDLRXQ2mAhNOEGzhfc859epdp1P
u/iuCpnfUkFLJs30oxANnD0d3Lm+BRuNNLxb6R8HzQs=
-----END CERTIFICATE REQUEST-----
`)

func syslogAgentCsrBytes() ([]byte, error) {
	return _syslogAgentCsr, nil
}

func syslogAgentCsr() (*asset, error) {
	bytes, err := syslogAgentCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA19LXIwTxiCpfqURlHEvgfng6MLksktZpfbcFvEIQfMzUvw4H
g4+y4vYmgpa6ypMQ0xps6/9/dQ4RaKAWO+EKs2PyJAVPDjkWuq2IkgNxLW0FKn9t
BUpKU4/kB9QIcskRYythlVZ1C3BDn0DuLbDN3HxAZ/emTkRGb2Qnah98lcDy5u6i
HHUwPI6tXUTg+0+W3p/U9SaV2naCyrUI9HvowlPL7tuYZSATDmrYo+qZGIsFf7Ma
Ox0eTU2P4AFFpBYudAxzfYVTiKw09y7AYKjFecL6HXmGwnkspQ+Ekz0HJFPS/k7e
P9TnZQestgdNFWkvuq4qyHhYQdhCaVOTUKXhPwIDAQABAoIBAGqHwvOhNAuPRurJ
PNNrzKMAe1CjhpHwTd/k4GrdfT/s5zJrHWBeJOGMuNOKzSbC0vIwwAT5d5Ny3zry
kib6XQrRUatgB3awzTxV/ex80HeosX0ZqtmKowd+JgOLMKRgBTobJq7NHzcHMgnA
xhA9jk+/8RagkjFd2BqRqDbk1d0gmLjl6uIO+E87NDMRZxlF7G8cCIj8MbxnwLlM
12Kbz8t9BP7R0lpqWceHW2ufK6XEquoCjHu8UrPI8FsNJMgGSrOquF5rxTa440fA
KkfEHbwo+0sTvrp1C7JcWszlJqzfrTckCv3F7LYVHzTAb3NRmIDaYKXPY64dNUXP
otxt7zkCgYEA/rdeHpOKqDpFewTtALhY/SKCjC6pOw6Lgk2Xgo8L9Tb32gQDy47d
bHZQHuAAFGknhsFuRfqFY6NwtXZLsJWlW9x1m/btzk89OX6o9SwufbjvYuYBgKCb
lqjJQVV+oZ3nVYcpuVhOz/Cu/SSlGEo8EP7cpI4B4kiRm4sgPFgpUV0CgYEA2OlL
NRo4eGbLLPYtVKihW0ea9uRp2YF+ZruzQy6DxZ5sueG8WqX/QZe5NKQvd9l+smwU
3kTP7cDi8AyNpKcolq+SgUHqb17pdmWjFQQ7j3Dwp3J7Hqe8QI/VLsIyEQXCnTVr
euFT+nFdQfTUdF/LhZusiij1FXxsLOz98NP/h0sCgYEAkcxSAnx/jKW2KaF7K8NZ
pKOBSE5ZLeW4c0CIrgHFXXo2SsOrjHPdSH08hT/Aq+444siLn2Czw4HFPQlWb+Bo
g3lglIK2QjZXHDbk7Vl5zxrxY5G2YHMOPCGm+U+/qTDiPrGcb2wdyKbC80FrgsjT
MwM/Nq3WZDkXp4nuTLxGAj0CgYEAzeqS2eN9bldvU8yT9gVrwKK2auEl1zUGUPKp
WAKlV4pw/vlb/NYO/y7QxDeFVIplq23NVcAPgE4XYfkY0hFaB8q/EvQHYRjCGwKb
kc0F2cNGwj98v/pOTR/+KjhynRRRzzoyQWH9fgf2lzGcKqnyJHFHl5UQLQiEDRYi
cGhg8QcCgYAhyzFu1sd7fiSD2scxkLnj88LNwscn1+iBUEq+RKB0GgL9Z76DKc6Y
7bEKKIDYxGjwGWMLW3+PAxARwXt7WCs/YkhUOwgaM8A5ECXlIVfC5olmvG+eIWoj
mePAP7sC9jIO+LH9fLu/uuLRiFbxytIFoSLVue1bkOwpZo6G+v32OA==
-----END RSA PRIVATE KEY-----
`)

func syslogAgentKeyBytes() ([]byte, error) {
	return _syslogAgentKey, nil
}

func syslogAgentKey() (*asset, error) {
	bytes, err := syslogAgentKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICjjB4AgEBMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNVBAMTFHN5c3RlbU1ldHJp
Y3NBZ2VudENBFw0xOTAxMTcxODMzMzhaFw00NDAxMTcxODMzMzFaMACgIzAhMB8G
A1UdIwQYMBaAFCR+xtOgULLZzywf6Aa+SQzJ4ioeMA0GCSqGSIb3DQEBCwUAA4IC
AQAau2w9CsGCBuktLKjkdFEjx3QEM+vjYQxii14v5c82HqAAcyE4LS0rx4bkMigv
codedj+2tE+KIoVkdLHjZBXltEjk2NZGTZbLPjT/tOzNPl+etpqTIZsSAbnIcETQ
PqVYf667R+KyUJy3M7Lz+XDZWPCokrp42WNRf0Md1thpE4vFq5dL0k5Iz2oiyg4c
qBclfHxOF1uY4qRTTXDDSTWKlHm/JJ0bDKMTiW5GWg+OrW8zKaOqNBPUzA1AgI+N
+SBX7JJ43Qdyxs8R6ELYIet5o8v6FtLxghb+pGk1vJjdY++mAgSiqMfIgiunMOP2
7O+vNTDhez3r+KbNQPO/bKSzx5AGZUcbAEmwJSyKUp5A6sTiPXRWDyTxUERcQJ0A
EfiFTxalIFytf3Ok4Km26lyoOsW2a/oiF972ENgPuuYb8Y9VhbZ95sVVsIXmpWTi
KMsjre++y0SI040TMILP4npZurv0Exys0d1jV85gYsAE+IkGp+O8iMCiH9PpMoqd
TwWGSM+m5BsFT8FIKuD2LR4QrgTNlK9uTozOzx5HY4oEtWOgsknvnQptOQ5C0DVa
n+J1ON9ClkoxO2L8j/XY5dCH+I8Nhlx10zW2wk8sLwXXb/bkbkPAWMtVo36bdBKN
gN4efD1addFcYxd0cJzes7Uuy6vs+JpqGpXL/pspkqKBIQ==
-----END X509 CRL-----
`)

func systemMetricsAgentCaCrlBytes() ([]byte, error) {
	return _systemMetricsAgentCaCrl, nil
}

func systemMetricsAgentCaCrl() (*asset, error) {
	bytes, err := systemMetricsAgentCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.crl", size: 942, mode: os.FileMode(292), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE/jCCAuagAwIBAgIBATANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDExRzeXN0
ZW1NZXRyaWNzQWdlbnRDQTAeFw0xOTAxMTcxODMzMzFaFw00NDAxMTcxODMzMzFa
MB8xHTAbBgNVBAMTFHN5c3RlbU1ldHJpY3NBZ2VudENBMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEAvSfcuxYjCLNfKuAmojBBegzajjBl5AWhbc6hho42
DgY6J9W02dCIn+BgvyN3fH/i4AEGu/Di750KQYy99weuWIF6O6cHIGzYYJW2BXy0
5qx+/XtkQP+fpMlTrut1VXvG2Ut895K8vlBBwYTlDTA1eSYeQ/PoBi9nTj+KAj4Q
mLk9QMwRhUWpqTxeYGdi7QTRDHUot77DOb4b6kqmYYPOu+lQRp67C1tinQxw/2JX
60MpNYQF680ALmE55jO6fcVBolnPD3uabH1cMe1kBFxpre28MPwiF7jDxtap6kMr
6l7eheuiMvjMWJxZW6o9GQ900MKo7FpUlTLexem2Mm2vH6s+cSBFjDhuezfNJpQi
ao12U+vNuKrxJUmTZ9YFu2MXr4yPiDvv10dBSxedwHYauPA3oF12Z7EQ3aqilWbJ
NsAl10eDDGKrjNKK8L2xUvFfwrwDG2h8rXA1ruSpfOphrotzPsa4fl73DCi2fjbf
pN3hFM4itqf8SmEj/z4pULS8YqP2mfxaBk+jAh6vt99mUuVvoS6cmw2e1M4ur4s6
E0xwEkwsQcWxEOAY0BBxqI/EM9QMRdkdHMbtdqmEoxotkbaSkHLm5sNnMBUrtrr9
gCfx2NrO40JMgHVI7dGi2PjW7NCu6ti75hNVCNf7DwCfkl0aD7/cAIuhV7GARTSa
Mb0CAwEAAaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAw
HQYDVR0OBBYEFCR+xtOgULLZzywf6Aa+SQzJ4ioeMA0GCSqGSIb3DQEBCwUAA4IC
AQBJ5y7Pt6odu6hbSzvVeLT4CZKgpQUN7YUorhCR0jHH3nJMtrdrf3ETODffMgK3
GHW7aT4mgihrOUHHajKANb490k6F/Wt656aeQRwX65WWY6oTSI4CnW7Gj/D2G0Zr
pbrFKph/0fQfcV1NESuggPeBk/wMcBFTxXJ5QTnTXzDQoUjP7IQM3O3W38fVME14
FMkXd1Cx8vBGEHtyihfVVhjUu8rsJzV8HaHZAqefRgjjJQhYTjFbDLPhDLcOeka/
DZOxFdf65WyiWXxEOitL8StQd3h5m8zOQIT0E6iNXI7Yreukew2IyZn5YKuvBb6R
j0f4hh8lu+X83zw/NE+5MsPhSv85OIc92HvEgPmK5pzspMHX6Ad/j7fdvyv+9Srw
U7mhHW8ILG4zg+sGPnBld/zkY7ErBQ9W6GgdwIH2FQbPxkHUxz8Z86iBYEbNFgAm
NUEFUip6teUY5Eai6f+9PSMkwA3LwrH6Sv+McbCnjjQhVem0GCKCEDSf8hdobkpD
B/JexpanwWZSk0Q9cZnW15zJwV8RaCTvRhNoIMOX92cmcJEwHXiCvD8iNfk7urwm
tq5lsfn3L4o61LiXNlCZvEmqMDuqoE0cTqypkXA4FB+c4tsKR5J2vbug6Ud64Dgi
M2hjUESIm075R4iT10GSVgarjLYN8ZxMDDDkXRmNBLxCMg==
-----END CERTIFICATE-----
`)

func systemMetricsAgentCaCrtBytes() ([]byte, error) {
	return _systemMetricsAgentCaCrt, nil
}

func systemMetricsAgentCaCrt() (*asset, error) {
	bytes, err := systemMetricsAgentCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.crt", size: 1793, mode: os.FileMode(292), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAvSfcuxYjCLNfKuAmojBBegzajjBl5AWhbc6hho42DgY6J9W0
2dCIn+BgvyN3fH/i4AEGu/Di750KQYy99weuWIF6O6cHIGzYYJW2BXy05qx+/Xtk
QP+fpMlTrut1VXvG2Ut895K8vlBBwYTlDTA1eSYeQ/PoBi9nTj+KAj4QmLk9QMwR
hUWpqTxeYGdi7QTRDHUot77DOb4b6kqmYYPOu+lQRp67C1tinQxw/2JX60MpNYQF
680ALmE55jO6fcVBolnPD3uabH1cMe1kBFxpre28MPwiF7jDxtap6kMr6l7eheui
MvjMWJxZW6o9GQ900MKo7FpUlTLexem2Mm2vH6s+cSBFjDhuezfNJpQiao12U+vN
uKrxJUmTZ9YFu2MXr4yPiDvv10dBSxedwHYauPA3oF12Z7EQ3aqilWbJNsAl10eD
DGKrjNKK8L2xUvFfwrwDG2h8rXA1ruSpfOphrotzPsa4fl73DCi2fjbfpN3hFM4i
tqf8SmEj/z4pULS8YqP2mfxaBk+jAh6vt99mUuVvoS6cmw2e1M4ur4s6E0xwEkws
QcWxEOAY0BBxqI/EM9QMRdkdHMbtdqmEoxotkbaSkHLm5sNnMBUrtrr9gCfx2NrO
40JMgHVI7dGi2PjW7NCu6ti75hNVCNf7DwCfkl0aD7/cAIuhV7GARTSaMb0CAwEA
AQKCAgA9S46OnZTKu/1p0msSgZqmJ0Ynb22FH4H5KE1VYf4IO2JbCDhroNS1IiuX
pLGSiYqGVi7NdjjDttrc9POV+ko36fUnIXAAxOS1H651Rr0ERv97uqF5Ipyj9I2G
kExcYBjGz1x2iXlaHn3AbQUgae/aC00hbgdRAclzJMnfAie0pcpAliBTVIivC531
lWsMLVRkug5wxINU0dMP8BLMZL74S5m02Lj57CofhCmVyFN/LCtNaTPV/n9BiEYP
39Fd8i7bokij1sTqxRC8KRYRB7VDJFeoc/vEPh5K78Lt48h2UTnAoePUqqTlTfzy
5E6aMVUEVSASPw9Lrclczug4nSxzAwh+NrbT659b6EKuMtwSC+paCp0gdK0Ig4bC
s0W7DI+RoqMkQZzz+Prxhosk1jjHd+0QlZ11TyXJAOKsU05+nFJ66VdQSx517ZDh
aQUOcNe6Vx2yHlnpXV924RHA3ATJRPtmBSr4pMvREtMBDbnLTb8QlDyxZuFPmWxC
amj8nbi+5KCjqIA6GJ5RYFhuBGsN615ZfPp+oRQPHjW8+CoNASE27fzPltclw2V9
LWXkX7wdRLOg92HwcaBjJXVDcQBxi0NIEAqzJx0yqXT8XxdHbxiqUALYZ4K5sfji
jal1Qd1Fvw5ESFvgpA26pB+HDQeXhPReCWfAY47DWGHkUXXRLQKCAQEA4oQRl4Ox
lpnw2c75DIbkxvblY+Dx4yu+qXNeVNy3DwONKpbJD7wL+1RpLzlSHDf3GRMMEKLt
WnXPw+HSwe3GQOEP0BEY0THqk6hUzF32qb/tTPKcoGwtOW2bFuYddrlYfOX9HFbe
GOWtknz13JDV9BZyB65URQKNMXhtXiYmnAq1dl7Yw06XTcljPeYC8+my+ARReIRS
Q67Ho6NNPa5KUvgMJZ6d4dhi2NZVkTEOF/b6cG87bjNSX/FtO9/wBxdO1CNTiAwD
DdV4SCSExUd9YJfw0/K6Jk0f4wjntZ4Niu3n8n+7Wxq1dKUPYi7zzZ9KlZFD4NPy
2oPLhb31YbJRnwKCAQEA1cbh+QUJrNg5B0c79uQLDKNCEAR2bYmrO4omSkVs4pQm
aAmpEVrFZxvswDsdra5GorYz55eqKbnT07wnKoftZTS1Mbg1hmA/HykE9kxpXCzV
DMvXqISEINUeAecs5fMtvNCObvP+Ruf2zW7f/eNqOmUlSPDKWWVOlwnl0GWjBJtk
eSrshUpTkr1H3HZ0VYRJik3spN6JSQHafHGrc0ze9agxXQGb49yUAiItgbwXfS8h
V722U2VsSVg+cg/5HqLxJZ2xGy8itT1Qxpt6kyVmSJXojI3HFBOEiIb4TO97vuKx
9Bx1/VUXHQ/GU7el1J6DJyneKRiw6s5c9sn7ZwRXIwKCAQBT/6PCawy9C2Mccjs6
4P8PpVkVe8JXes5eajDuCVc9ExUTWQ1Ab3yF/BxxbbE8U6inPL/5n2GjbRLZ0fFl
BvbA8nT5tI1ebkNN9FtV2fZxpoGqSkG438S5iiK8ECOW9k6RKnx9ON1toCaIrxxB
adhdhsFMheIsITEYyk7MXhttPC9ksPFzI77KEsdhmd04dE5w2LEZnwAepz7TOOiY
2fwn3mIqxTJJIQQu4vSiPe27B1SBw03npNKET7QxQu7wwjzyQBNm3QV46NOM9TXj
LoqY+l9NSbKsJ2eOuquqVu0wut6Lt8BTnYjys48L2tuAQfTXmCHyysZBMCSV+QZ4
7zaDAoIBAQC05LYSodCuEckv/3ceU5mF+B/OrfgIeJYMq7n63wRkNjjJkGMf7E9e
EKMlhuB2NyJOTR9euVekNzqn0G7T7nFTUmaAy/9+1bKUC4HHaKE+/jDJwzOZxYiI
v83EjnnPmxb4zwG3oX9pQJ/29ftUOzuIbk4+ioKvYqo95IIy9c4b9+HtJgU+RMaz
RLeqNhH6yxXvkkDMwgIpZQgchZMu3b1M4iXjLZlcFyqnI4SeYyr9IwRz2nSN3STk
a2dr3VhQNFEaI3XaKuiTtG7FoIr4OI10nmVJii8LLfjYDl3NvFhaDjnG9s5gr7//
N3n7HUuVvwv799GltN7/0d+YdRHm+iVBAoIBAHUw7TPXCo7bF441/3kg69sPCghl
HxOOGjLLxrmdCZNxu4UIdSQTcRwUAdDNvr1LLCmaC2Y4j6zi6DVGNQT5Y0c/G8o8
cpedwJ5cRPCy8RU6s0OQCDqAySsz9YQ36f99n/77wAy1DOTZffeDA4j1VkZHYvkI
eZ/bzfVmrSb6X70R8TrM4c/AX+736zspEBRD/WNckl1JbOLN7+q1Ol8lSWYga9pr
K1TClC7Wtly9QkWIQCCKMfvTY/v1IMc9SOszUIv1LdXYdoSSHyWXtQvD+pROnw+8
7c51/kimcC0HfBAbYbGzyifOwn3UVc6wwBd2kZlzDPRZI3Rq4cGN9R/ikn0=
-----END RSA PRIVATE KEY-----
`)

func systemMetricsAgentCaKeyBytes() ([]byte, error) {
	return _systemMetricsAgentCaKey, nil
}

func systemMetricsAgentCaKey() (*asset, error) {
	bytes, err := systemMetricsAgentCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1547750018, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"binding-cache-ca.crl": bindingCacheCaCrl,
	"binding-cache-ca.crt": bindingCacheCaCrt,
	"binding-cache-ca.key": bindingCacheCaKey,
	"capi-ca.crl": capiCaCrl,
	"capi-ca.crt": capiCaCrt,
	"capi-ca.key": capiCaKey,
	"doppler.crt": dopplerCrt,
	"doppler.csr": dopplerCsr,
	"doppler.key": dopplerKey,
	"expvar-forwarder.crt": expvarForwarderCrt,
	"expvar-forwarder.csr": expvarForwarderCsr,
	"expvar-forwarder.key": expvarForwarderKey,
	"forwarder.crt": forwarderCrt,
	"forwarder.csr": forwarderCsr,
	"forwarder.key": forwarderKey,
	"loggregator-ca.crl": loggregatorCaCrl,
	"loggregator-ca.crt": loggregatorCaCrt,
	"loggregator-ca.key": loggregatorCaKey,
	"metron.crt": metronCrt,
	"metron.csr": metronCsr,
	"metron.key": metronKey,
	"prom-scraper.crt": promScraperCrt,
	"prom-scraper.csr": promScraperCsr,
	"prom-scraper.key": promScraperKey,
	"router.crt": routerCrt,
	"router.csr": routerCsr,
	"router.key": routerKey,
	"syslog-agent.crt": syslogAgentCrt,
	"syslog-agent.csr": syslogAgentCsr,
	"syslog-agent.key": syslogAgentKey,
	"system-metrics-agent-ca.crl": systemMetricsAgentCaCrl,
	"system-metrics-agent-ca.crt": systemMetricsAgentCaCrt,
	"system-metrics-agent-ca.key": systemMetricsAgentCaKey,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"binding-cache-ca.crl": &bintree{bindingCacheCaCrl, map[string]*bintree{}},
	"binding-cache-ca.crt": &bintree{bindingCacheCaCrt, map[string]*bintree{}},
	"binding-cache-ca.key": &bintree{bindingCacheCaKey, map[string]*bintree{}},
	"capi-ca.crl": &bintree{capiCaCrl, map[string]*bintree{}},
	"capi-ca.crt": &bintree{capiCaCrt, map[string]*bintree{}},
	"capi-ca.key": &bintree{capiCaKey, map[string]*bintree{}},
	"doppler.crt": &bintree{dopplerCrt, map[string]*bintree{}},
	"doppler.csr": &bintree{dopplerCsr, map[string]*bintree{}},
	"doppler.key": &bintree{dopplerKey, map[string]*bintree{}},
	"expvar-forwarder.crt": &bintree{expvarForwarderCrt, map[string]*bintree{}},
	"expvar-forwarder.csr": &bintree{expvarForwarderCsr, map[string]*bintree{}},
	"expvar-forwarder.key": &bintree{expvarForwarderKey, map[string]*bintree{}},
	"forwarder.crt": &bintree{forwarderCrt, map[string]*bintree{}},
	"forwarder.csr": &bintree{forwarderCsr, map[string]*bintree{}},
	"forwarder.key": &bintree{forwarderKey, map[string]*bintree{}},
	"loggregator-ca.crl": &bintree{loggregatorCaCrl, map[string]*bintree{}},
	"loggregator-ca.crt": &bintree{loggregatorCaCrt, map[string]*bintree{}},
	"loggregator-ca.key": &bintree{loggregatorCaKey, map[string]*bintree{}},
	"metron.crt": &bintree{metronCrt, map[string]*bintree{}},
	"metron.csr": &bintree{metronCsr, map[string]*bintree{}},
	"metron.key": &bintree{metronKey, map[string]*bintree{}},
	"prom-scraper.crt": &bintree{promScraperCrt, map[string]*bintree{}},
	"prom-scraper.csr": &bintree{promScraperCsr, map[string]*bintree{}},
	"prom-scraper.key": &bintree{promScraperKey, map[string]*bintree{}},
	"router.crt": &bintree{routerCrt, map[string]*bintree{}},
	"router.csr": &bintree{routerCsr, map[string]*bintree{}},
	"router.key": &bintree{routerKey, map[string]*bintree{}},
	"syslog-agent.crt": &bintree{syslogAgentCrt, map[string]*bintree{}},
	"syslog-agent.csr": &bintree{syslogAgentCsr, map[string]*bintree{}},
	"syslog-agent.key": &bintree{syslogAgentKey, map[string]*bintree{}},
	"system-metrics-agent-ca.crl": &bintree{systemMetricsAgentCaCrl, map[string]*bintree{}},
	"system-metrics-agent-ca.crt": &bintree{systemMetricsAgentCaCrt, map[string]*bintree{}},
	"system-metrics-agent-ca.key": &bintree{systemMetricsAgentCaKey, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

