// Code generated by go-bindata.
// sources:
// test-certs/capi-ca.crl
// test-certs/capi-ca.crt
// test-certs/capi-ca.key
// test-certs/doppler.crt
// test-certs/doppler.csr
// test-certs/doppler.key
// test-certs/forwarder.crt
// test-certs/forwarder.csr
// test-certs/forwarder.key
// test-certs/loggregator-ca.crl
// test-certs/loggregator-ca.crt
// test-certs/loggregator-ca.key
// test-certs/metron.crt
// test-certs/metron.csr
// test-certs/metron.key
// test-certs/prom-scraper.crt
// test-certs/prom-scraper.csr
// test-certs/prom-scraper.key
// test-certs/router.crt
// test-certs/router.csr
// test-certs/router.key
// DO NOT EDIT!

package testhelper

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _capiCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICgDBqAgEBMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMTBmNhcGlDQRcNMTgx
MDEyMTU1ODE5WhcNNDMxMDEyMTU1ODE3WjAAoCMwITAfBgNVHSMEGDAWgBTClxXN
HJGlKKgbkgNkaSQmyH/AkjANBgkqhkiG9w0BAQsFAAOCAgEAHIl76tNJK8+kprZD
wPp5Sl8FxU+ajw+xkLA4tqr0g2J/B02jUMDXIMLYwg1SKbT2NiOVoZStVMkzP5UH
wya0yR4PXioXyZ+irScdQPQuUNHfa8SX2A1cVSJ14ej5DCj5G7vGX2Gp4tuc8lwr
VlDu1cUW437CymwcQLgjKaJ/jNJ0HEcadNnnC2/4nrMM3vjq6l/TRDjstYK1PA2h
4EAbBXl1JGsZ9E9zFn95BAPn8zvG0tlGbwh/DrH6YeTdh8XBU7qWvzUB2buVlJeK
AiayPeFFH13U3G3beX6EnZDGGPfnlnKcxt1B9jq14qKqlELSUnbzyS2j5CpKJEDX
6ISc3rNFnfR0OGaCJgjwmSrNnBCfpAPuW8iKVITru9og60xMO3BQgTEzR8XDulSm
y+qIZWxeZS5AM5WUidefQ2tonyeybV97JbaWd9aWgM+hWsIl1nOsJkRJ85DkSln7
/qIOrvVVOE0ZpMqDm+8eVTVAqqyeeaR7gy6oon2eEeJ21uFwO8kybHlzoeVuZPvJ
zzTYb03fVHeCpJamJbh/L6S7ofGJ43QNRgVLh+aeRsuOJShA5VS1CDrRhVxWruVK
Sa/X1CsJ2KJWcrQEzv2CCnqhxdQKR/3uPsn6d0BopLQFYHis4ccxOzSKyOERgWzX
zzwqPM1pcDaPNY/85rLGpq9C7qk=
-----END X509 CRL-----
`)

func capiCaCrlBytes() ([]byte, error) {
	return _capiCaCrl, nil
}

func capiCaCrl() (*asset, error) {
	bytes, err := capiCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crl", size: 922, mode: os.FileMode(292), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZjYXBp
Q0EwHhcNMTgxMDEyMTU1ODE3WhcNNDMxMDEyMTU1ODE3WjARMQ8wDQYDVQQDEwZj
YXBpQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCYkBzwb1vZHmiU
XHRaZ9l41Tfud4ZhDmBF0sxJ4rzlLAiUgzYnqvjOoPlsqsNXezEM8JZ2hmUpMfiH
boSS8VckOl0v3vXMDPoczFskCermvr0x6DT1wnaGeJ7BDq58EVd8XCpsyqXWzByj
rSAJMGPQXYnL7aLFRtLU7yfoqWyMaNR+fNq/fVrgBqJiaZvy6Rjhynin+0MyIeQ/
Sik7gZmwHKoXZviiOeSJ+QX4i95ZHtcSg/qO8qlg5jrLSm4rD5/U0hxEscYDr8/w
yW8XvTBF00d6GoaeCceurQOJZ42448LO3jq+N6UQnl+vI7YGyctN9Qu/ExZ51Ini
qpPBVXRIXCgqq6+AjX4/UzZqCsqhgoNhZZsSSpoS1yRdblX39vhpjbyWGNmsZ7nA
tiCAuw+9zskU9yMF6XMlxwIlI6tc8nRKotCoHGJjjQZlIcNkPlEmJFpdkdxnPgIn
V8InrCd4PEEgEGioD6GOmhRK70aMOFylzFWSmKfkuJQEGEuAUBHgjUivwJ/EKKGI
rQZBboN8Sfdjsm45mqdOCWTFTTX8RiD+k7zQnX3/t/gCBqZpZ8bm6TQwW2I4Cdqn
FtG69zOoPvVRcZg0rvBUu2ddRNJPv1CP8JsJ/rYeIOmYT5R5mgsYYgcIz2vsaPP5
0BFlyBLbQZdMOeXzxDg0f/Dyv5Qy0wIDAQABo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUwpcVzRyRpSioG5IDZGkkJsh/
wJIwDQYJKoZIhvcNAQELBQADggIBAHeRYj9MWthMDRBs14UldZ1f6T0bRPXDq9Sb
67rS6jPI3L/ATY32CBlsUU7ftN9A8KbNFACMeO1JpUg6QS6HOo3AaenUrJ+UHTiW
NBBte6mQGjbycRGIDgtAPleKbPR1U6zJraTyRleA5oGtvZMG29l70jBAsnyZ718R
CyNvzKhgBGTobSIkXEs9R2m3jQ2VaoG41Tb+aXjnZHB7q8VEk2IF21eH1s3RZfP4
p1xWlNhWc1OYAUGlrIV8pYK6D3FI1HUYylIrlGH8jWAQyIapuTD3c5xkQ7P+hQOP
vUhU9FOprVR6zQoHbQEna79Kp9QX0qCU+iwH3I730js2prTZfjTjAUyDWA2VSZLA
HiAuxuBc8cr+buzYpHltoOR2Kzk4t7FGi8Fc/ZgTJRdhVx9RwvuI0vjZgdxTl7Fy
NhnIe0QbFSW2uWN6MHHYLl0cr3anY6zgIHteoyuDoVL+zWi+FxMePW4Ta+t1Szbv
af4DaWpLCgVtwgITKZ/gNqCQzVfsgdtvlMwbNLqh2RlDaZgJeKxEiNWYWf8woXSD
rvs/OxijPeih5aEpNw5ztWmuL9Sigrc3NE9wLuVJKM9IQkCsq5GA89Ef/KZV+xOd
fNgAA91V1XjjaA6diIQ6QwPq4ch1OloZbIGo9fRxl0EG9M/JcWzm8iCuPbb9Cj1b
zmhKWqx6
-----END CERTIFICATE-----
`)

func capiCaCrtBytes() ([]byte, error) {
	return _capiCaCrt, nil
}

func capiCaCrt() (*asset, error) {
	bytes, err := capiCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crt", size: 1753, mode: os.FileMode(292), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEAmJAc8G9b2R5olFx0WmfZeNU37neGYQ5gRdLMSeK85SwIlIM2
J6r4zqD5bKrDV3sxDPCWdoZlKTH4h26EkvFXJDpdL971zAz6HMxbJAnq5r69Meg0
9cJ2hniewQ6ufBFXfFwqbMql1swco60gCTBj0F2Jy+2ixUbS1O8n6KlsjGjUfnza
v31a4AaiYmmb8ukY4cp4p/tDMiHkP0opO4GZsByqF2b4ojnkifkF+IveWR7XEoP6
jvKpYOY6y0puKw+f1NIcRLHGA6/P8MlvF70wRdNHehqGngnHrq0DiWeNuOPCzt46
vjelEJ5fryO2BsnLTfULvxMWedSJ4qqTwVV0SFwoKquvgI1+P1M2agrKoYKDYWWb
EkqaEtckXW5V9/b4aY28lhjZrGe5wLYggLsPvc7JFPcjBelzJccCJSOrXPJ0SqLQ
qBxiY40GZSHDZD5RJiRaXZHcZz4CJ1fCJ6wneDxBIBBoqA+hjpoUSu9GjDhcpcxV
kpin5LiUBBhLgFAR4I1Ir8CfxCihiK0GQW6DfEn3Y7JuOZqnTglkxU01/EYg/pO8
0J19/7f4AgamaWfG5uk0MFtiOAnapxbRuvczqD71UXGYNK7wVLtnXUTST79Qj/Cb
Cf62HiDpmE+UeZoLGGIHCM9r7Gjz+dARZcgS20GXTDnl88Q4NH/w8r+UMtMCAwEA
AQKCAgBLMz4QhdOQQhzqhGgV5/qaRP883E2wqZVq1W09PjY+AGZ6TfLzuqLJty87
ETEYffC/oBeKdNSIaclHeIKAq9V4Vgx4/D3MRtlCOLj0Gq9e7cX0Q7FXMnOZ9PrL
zqDTJvkoo4WF+p2kMxgq1btkzCVnH7Q8gPYqp65kpz3UwS5wR3v2nTR2DyQsKRkB
yWzFX4CUS2kN5BxLKcmIKNYKLufCl16ACpGj5UVxfP4kdU00QK9iwQtQSuyShumU
KywCrcDq9mZYtggU6SRmW+QWn3qb8HjbBxgz7j4vK7kCkbiZ2iq8LW5nNKZ4ephP
jBq9XdqIorEXjiEWDF2rDMmoEqcuAOfPXHq31z0zdrYZEHLaKpZdmUX3GaDayeu8
1HLerI9XcvooIfPTBzxooAp7hLwqzkTVER8Cmj82MFM+qwf4+z/JyF1AYByP5t9P
dxMoloQxw2w9++vo64tIGrrCZ2GEDuLU/zVYThTYaHw6bmig7Xoopn/2xbkmNSjh
Nt5sSluGz7MVbMF/xyZ23T7VcptwY4SOjOK0gMPGKcGqphhKprXF5jgJ0+/Tx+KE
xh9SfwVM7Dy2Iea/gp7MCgnEU34mjFepvj0wCsU8olD74seEYthcWbAuIZlc+3f4
/u27WC09crKBty7mi1KW+5P/RssDziLZMR2X0t7VFNXcCTPwAQKCAQEAw1uJlJya
edYtjSvw5xu30r6WvMEbgstZ9ZZfgOeJvc99tuCZ4le9kbBIX0aIO7xUR9hmds0k
kWV4qgZslWxvnPKhlQw6t1lemfq35IAWgR9kf07658SElY+hP5HZgHGUdhuW96b5
YbvsVHTYJFzh+EVoZIJqGwvDG2aGQrNmSkSX9Y+F9SGqBlp2iiqLwkeiOc6Q4Inx
DMqYYYmvFW8jJrp4GkjiTQZEeg40MFqFNc6u8/DnWIJiEoWz36hekXeHNKalgzks
vMankbxhI6KqP0RWZ55neWY5uViFnXrRCos0244sXFoSxHWuMLG0J9uKZM86t0Lg
/dm93Q9zhqk/UwKCAQEAx+vRnmlWyEzRlYd+yxXp1Ww5OmJklqy0vPxgkqXxNR49
GMe8l6o25SFPCDaxf4S9QZX/GJWg/D04l4UMYY+p+uew2bm1DhPsc15sheVZ1bD+
UcFz2AqpCKbchXazFTyVKFvF8T3Bavi6gtQLn6a46QVwoC44CptnHHzQoj6vklso
jR7wfBBTH5DBNhYDo/wtP8ucyylgPMY2Pu8V5xyOUj36RTq+7LrfMM2uk7JGGCsY
gCd/i1S64myLbUHYbNDYDLsIkmO8cIk4tGaoCNB+PP+tqdq372FmtkR0BRkR4Xfb
KENx/cdwcreWszGUwf0o2W6emirM6CuuppkXAQBOgQKCAQBvu2v91m+3nVriMi6P
T9gcLaty+5NrhDjIcJ/gzwyFxiWlseHxhbNDnypVa7bBS558lPVNn1j526pevFvg
Pmu7vT3TTHJMqU2lDbOdefDlGvpUoex5IHmgPMzB2f4nK075GiCHNjXNwziQuV9h
tMn9QF1LlxdurpSBmGrTvV2UvpSW+uZn5EAlcBn6Pgk/Lc9H9q//7IU0hq8OojvE
K5NUNDQ6/FKKMTp7AKKywSMNOk/v72mxwqiq5VOSaO7ljhKDd4iUe9/tfEUc4jxA
sGlk1AYDL6MI2QHM0ydggX0L5cBujmsqys2PFatx6EEcxsDplWiEpjiel6myxIKT
kztHAoIBAQCzzM24d6qZ+CSiI7sP8QRdcrjBXo5yyJ7APQapvV6C1FBEghaGHIrE
ZcGLdI0MT5habQmA1cl0Mac89mbdM3S/eDKgjhlcsOR+GdTmUxAJVOZVJvQFwAio
BFHeIpQLLHJFWsxaG51hlJNBaG2Px0UUJVVWalryhzMj9sk4scH7kcqVqNbF7XSk
te5es0vQ5tLXRkscmHi6D9XnoeUD9rW1F5KHQr9Fbwed/83bfYD26YNedqeJ6skt
LEv1FjwMGYPFZ0zdQ5/NYkxCSvUjAEgYmiZY1aGJRAM5N7VUhGiFa+MJgib6A62J
Lr31KUlNcl6Ttp4jrwycXfT0VkjPGLSBAoIBAQC3H2dYKPui79/Etl4GqgQ+fJwT
ewjBf/9FZgFhm8Z1vjoSk+kw/ffJ4y88FBxKsa/bdL7c6NTMGGA15xl+btLiksrg
KgabX8OeCODQeY8rP1zeyNdO79d7B6nBYjQvtAPZ2TLaSgOx1uM8Nkd+5WM8dF1w
Nn2n0/pbjLHvnqNf7TBZ5kJRbVFRjOIUTLzB36g4C09QKL88Aq2tG1aN21uUnHKy
c5fxFwz2IJ6RePdYDRpr3692I0PPwLYZcgYp/Wa8Copb8bKWG0hAklzjm0Nf1EVg
6RnYDUpwUnbZeGZmmKXo4DrS2ETqkHVKPkTjOIzoidKZRiDS9Hqlvcpkl/aN
-----END RSA PRIVATE KEY-----
`)

func capiCaKeyBytes() ([]byte, error) {
	return _capiCaKey, nil
}

func capiCaKey() (*asset, error) {
	bytes, err := capiCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJjCCAg6gAwIBAgIRAKufK22pi4bHLtIQeDWNlPswDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xODEwMTIxNTU4MTdaFw00MzEw
MTIxNTU4MTRaMBIxEDAOBgNVBAMTB2RvcHBsZXIwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDcgMwWYoeGqBCtZj226yyZJBMLJB5xrlsgBwGAWVmUsZNh
D7am3xDK7HJZGNTFzO4NiBlcZP8zorX+o3ketus9/KlLioaGFMG9GaI/6N3xYyHK
gN8y33BAYDc19EmUZPiTRy+/j+H3MJrAgCFo2EUzF8LylfB6fGfFY8zYikZbO8gM
28YBFwjSBxiG0HQuHPBWlRVs2F5DZMRH0h2ZoArL5jtW9Q7eAAGFvExXDvR3KPK5
SaRTvuy1V9wCJfvxzBmhwNyDUTStwzSjnR8hZOV1JcLyxmXCF5sKI39vCmr3V7oU
rCVUJhG5poMAwKgAa8m+K+mTu4ex3jT+VP6qKAK9AgMBAAGjcTBvMA4GA1UdDwEB
/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYE
FJr9WwfiTHiz0ysqiN00BcUGkF5aMB8GA1UdIwQYMBaAFHgr5wPEgDJeozznwY0B
Ty+HuGzpMA0GCSqGSIb3DQEBCwUAA4ICAQADre01CgdkTmg4xESWsx8iexTRorIc
aLlSw1HIvZw/CtYii2yLAVuH1m8qvD4LDP5XGN1Y6fSXFJfZKrm1cWIZdN9F6VtA
vW14PntK+IoUe39HgHygQ2/z6a/Uj/HriT0IC6CHQtxgZJ5nBtIu2qv8mTFbDs+N
XRn8qfHQPj0bxvMY/XZK8iysGgXXfzJoBP19iLlCnXdZDm3KZ6ogSis+A/T38im0
Jrng1SFG31pxFVjOweNg8KpjANbQFFqEqUqwkuiVRMA85MZVa4+7PsGe/Sd6VGf2
Of0n8+oaVK4gcC4em+Ov9cpLDwWpnrB/5Kt1XSUbQFh3/EVeByR8KrQPDc9Un0+l
Wu9uIenML7a9f9aiSsq765FaiGbXRSUoNwGdqKaCoht5kJAgUeq5Q2oqUl9YSxQL
1kTjJ78cxAg3YmGXEtXhgFy0r2MfpUM26hdZbMR/5PZPWVMcs0lDS8GOkcc09Tv4
ThQHILsI0KecZB+RZXWrzIikdWL+CqKTpzJ/uvKyvuWIgiVa6t3wq+c0WCyrH0tV
2Aq1BDp+oKyf3i1fLNbV7Zstm8dhnWrWDNEWyfp3pp2Glz8x2hQemFykVtiuclK4
Ni6rUT1JrQV0n8ExH/QuMtHxmdbH/bo3VCVqNt5KBWbJZX5F0YAExYeOabpmRUwc
2SzwdIdM3ZWT/w==
-----END CERTIFICATE-----
`)

func dopplerCrtBytes() ([]byte, error) {
	return _dopplerCrt, nil
}

func dopplerCrt() (*asset, error) {
	bytes, err := dopplerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.crt", size: 1501, mode: os.FileMode(292), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVzCCAT8CAQAwEjEQMA4GA1UEAxMHZG9wcGxlcjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBANyAzBZih4aoEK1mPbbrLJkkEwskHnGuWyAHAYBZWZSx
k2EPtqbfEMrsclkY1MXM7g2IGVxk/zOitf6jeR626z38qUuKhoYUwb0Zoj/o3fFj
IcqA3zLfcEBgNzX0SZRk+JNHL7+P4fcwmsCAIWjYRTMXwvKV8Hp8Z8VjzNiKRls7
yAzbxgEXCNIHGIbQdC4c8FaVFWzYXkNkxEfSHZmgCsvmO1b1Dt4AAYW8TFcO9Hco
8rlJpFO+7LVX3AIl+/HMGaHA3INRNK3DNKOdHyFk5XUlwvLGZcIXmwojf28KavdX
uhSsJVQmEbmmgwDAqABryb4r6ZO7h7HeNP5U/qooAr0CAwEAAaAAMA0GCSqGSIb3
DQEBCwUAA4IBAQBSYRhT96kdtweP0G/3JD/jwSPABDZg++zIrPtOtabs9DT6EvBc
Tt3ZugxohcyibmwA1noslDrCIbyqI0b8605FMG1uYjJh1S2/QDgikb75rkENSgRw
00Q7i4p4v2/MdTwN2XbN8/vOT0BlXA+7ll5nsZSPAeJme75A6or9DApI+B33QYt4
Qcq70VH3RSTQe3avfpz3Xvh3KfVQwLHbFiZbA+QGO6yLCHM/vg/cAAqblTAZjQUB
XdAKg/RU1lUDINVKyWhteJusk+sbiuFS/rtOR2Z4CkMVSBw9VI+xT4NhEUmY1J/I
vSdsd+GfN+/aJfOdj0b0mrmDPo8SbJI5RXr2
-----END CERTIFICATE REQUEST-----
`)

func dopplerCsrBytes() ([]byte, error) {
	return _dopplerCsr, nil
}

func dopplerCsr() (*asset, error) {
	bytes, err := dopplerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA3IDMFmKHhqgQrWY9tussmSQTCyQeca5bIAcBgFlZlLGTYQ+2
pt8QyuxyWRjUxczuDYgZXGT/M6K1/qN5HrbrPfypS4qGhhTBvRmiP+jd8WMhyoDf
Mt9wQGA3NfRJlGT4k0cvv4/h9zCawIAhaNhFMxfC8pXwenxnxWPM2IpGWzvIDNvG
ARcI0gcYhtB0LhzwVpUVbNheQ2TER9IdmaAKy+Y7VvUO3gABhbxMVw70dyjyuUmk
U77stVfcAiX78cwZocDcg1E0rcM0o50fIWTldSXC8sZlwhebCiN/bwpq91e6FKwl
VCYRuaaDAMCoAGvJvivpk7uHsd40/lT+qigCvQIDAQABAoIBABQKEIIoSjDOrVVU
6V7qWI9CXAizK6EhO17ZxCUp+Z4t1TsI9oyL0Tbf7jRysUOYsDnCmKtw8lB7BRcz
PBqyfQaRI8GdwUQGNuU8oyYzv5fkbnm85Iv3CniPRfU9UkKOOpkH6yr5pIuWeznr
ax3gKcnO6wSo48X98GBcBY3YYzR/OxhxzZolpLHqYO5PMJ5+qeItGzmn4SDJsXSa
DZqmw4g8Gy2is15yIkfDGMaGulV5Tlw3zLb01WtlIFh9IYA5qc0irS9VBlI5TKkG
ZADLgStXfLEqAmS3stx3mQrOH9DNw70OGumXtBpQ6VTpJWU68BybKGaVOlNwbgZh
bRY10HECgYEA3/dk4hvsQj0aKT/5bi5Q1ICcGjfucVpIUMs4VQfQYoA8YBKPud5u
Oy1UDj1Ao4xVJ7fxymQUKPUzsRYdvVW6sSsnHpmIwNoXoq6b8PY638mT/pkY0z+l
jZfGJtNtiRaFySTkLVsgr6wIAlfd0HXajqSbpjAobAUo5xWZoSKYS1cCgYEA/AqY
J/sIyKnwxEPpdzocjfWmkVpCsTkbqr+sbcL3c2KLn1yOjStYqeVUGp0uCu8kFxqG
D0mEwKViEpxdx2fWhZIWoiWE0FsqVCKbLuQt5F2odcBf4U6a/UdG7kDe9jYzOpKE
Zw0GK3cjlu6VCBg4oWqSoH+zZDMJfGFy1bjzqgsCgYEA1qIqBh6oXhpcdeefTJ4K
THwsHVw4oFzbLMJ0a9ifNaabNZ7UKlYl4YRhJ3w/8/xKp1O63jDmuRGzxiPhwE7m
KV+nj8WnrtnTCM65F0WBynFN6RIjHl/Ccl1fQloggN4avFckbOsF+hStYEGAi4RG
Pak2mR9RvaN8PWkP38JdnOUCgYByigIB0VR5lLlFCDPWKgOGBAfxcFp0naZUH40l
yH+Z4UPgZTinMPa3Ju/ktF+TOoBlO3mHAvsgbUg3evYnQ6o6w1wjzfcglP2UhLGP
SsUMTf/bm1Q3WPiYd8blSXfJ3nHDgYhIKKQQJrF2yu/RYOiDeqIt7DrDI2qBKuv7
8nRRZwKBgQCz2uwwanZ/z/zo0ub8g9SRDkmrMln8agKJt/R4WXIU0w14/tU9sOKv
c3aWMGX4/6vyL2tX5ymc4DveUuUBWjOrIfVD4v51EojMOWXsQOKnxB1/v/+eKlVj
HNzEEsnOrf/XiPtObZgjXFCPyWohLqd4ClqmGzcAqy1h8r727Z8oUA==
-----END RSA PRIVATE KEY-----
`)

func dopplerKeyBytes() ([]byte, error) {
	return _dopplerKey, nil
}

func dopplerKey() (*asset, error) {
	bytes, err := dopplerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEITCCAgmgAwIBAgIRALElJt6RMtq64HR+y48KFMkwDQYJKoZIhvcNAQELBQAw
ETEPMA0GA1UEAxMGY2FwaUNBMB4XDTE4MTAxMjE1NTgxOVoXDTQzMTAxMjE1NTgx
NlowFDESMBAGA1UEAxMJZm9yd2FyZGVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEA1h4dZZxrw4Zx238gijTDaH5dmvgkmL87AXmetrjRCtBPTv+drG+a
3uDKPbnNbxg4WE5c5PaJs7tYMWE93ToOJvBbMcbrxM7mVk9kUDEEeUqN5g4BXysG
IpiKjBFVmL6xrWionhv4+xMaQ3BRMJS6c7wg4WRhr6WninfNr79kJJtZJhvNiix6
fjtTOSS2ql9Sk5WhmPEMiU10VSFmDk4jvJI5Np9U4zlkddM1kEIsicbwoc1RFchx
FgZyf4hprU+np50naxx0IDRQnXul9/fXHODG0T8b4rHE6hgVouqfqBQTPee5YhAL
fIBXEemun/5Sje8o+QWNAQetkTMH1B6bhQIDAQABo3EwbzAOBgNVHQ8BAf8EBAMC
A7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBRHJ6wf
a72r7WRuB+vp3UicK5Wr3DAfBgNVHSMEGDAWgBTClxXNHJGlKKgbkgNkaSQmyH/A
kjANBgkqhkiG9w0BAQsFAAOCAgEAf2xdBTtex7YlHPbrmuS25cc+7ZFYcOzWJLQG
NGSJX0QA6nYrhSO8PxhshYtrGbFOJC7sb6EqSgC+QjNlPfWFL0LpyVc4Oq2BihX4
crs/ijzd2TdEZckECFt/DXHGuagVFLQCkpEv+GSz5UE4lu3RKCaxYts8MV4pfi2r
ILOguvlyzW6LLk+99ow3B1WtBYhIGY+gdfUid+GJbd1Gjb6e1oMWSdRbXq17Jm05
oAzMdIC7Ojtj0TbGaUQcj83H42W8dmLRY9lXbZfgqWXHRfOiihXM9zTr5PMAIk0W
hLEoGLRDPdbp72k5fVAk7cIbfI2V/HWRGpmbfw7MV3S2LyTt67SdC0dV7EknUvYb
/GCtxENLbqu6JnRBboysDcSqBNeIjVoYCxQlhasFrjVwRWDjUFU9IgYOi1qhjGwJ
7jl2XvPhxQynGBsBfiABnLN53r6HiJGE+AiVR7IEaARlOGauV14vvyZABT3UkpUu
AKUPpY6oMeapHZzYAGTQP8YGYUC0UJx6Y13x18/Entn7kE5t/gh7d60pM1ENsSJC
BlvPvK/HjswMsfX4euYdaK4C85qWwwxWZmEwpcAi+Xa5v44+iG6Ux55gB95zpC8G
HfZTWUhHjMUH+6SVHZvSlYDGS0KaTlBfXLmynjCn77Uon3nlUDvTXtG6zRYuJwUB
Jl+z0SM=
-----END CERTIFICATE-----
`)

func forwarderCrtBytes() ([]byte, error) {
	return _forwarderCrt, nil
}

func forwarderCrt() (*asset, error) {
	bytes, err := forwarderCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.crt", size: 1493, mode: os.FileMode(292), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICWTCCAUECAQAwFDESMBAGA1UEAxMJZm9yd2FyZGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA1h4dZZxrw4Zx238gijTDaH5dmvgkmL87AXmetrjR
CtBPTv+drG+a3uDKPbnNbxg4WE5c5PaJs7tYMWE93ToOJvBbMcbrxM7mVk9kUDEE
eUqN5g4BXysGIpiKjBFVmL6xrWionhv4+xMaQ3BRMJS6c7wg4WRhr6WninfNr79k
JJtZJhvNiix6fjtTOSS2ql9Sk5WhmPEMiU10VSFmDk4jvJI5Np9U4zlkddM1kEIs
icbwoc1RFchxFgZyf4hprU+np50naxx0IDRQnXul9/fXHODG0T8b4rHE6hgVouqf
qBQTPee5YhALfIBXEemun/5Sje8o+QWNAQetkTMH1B6bhQIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAAvtmw2gIodaiyefNRs5JNoYnvStwcW9vI1m/VwA/YMxDQic
ShVh7v/Y2fSHHGyxkAraGA855yCxWunVkmiUf6g9BA793K/JplIgyafiUnLHdT1u
ANjqVGGLgOvm9o0vtKwqPFYCIo+rv+qP0lYggNtAJyoX6xjfN6naUqIL+/XonMi+
u7GO4tecQP9zV5P6OKqzy0ap2gwqpXU+JMCVwU5OwzfzkxcoxCx15GyUt7XtR+eJ
nNnRjNo63Npn+TpIytEK8YkEBTDlniTrz7YEdSHDQfEFkW4EgujROWo0npqqE9Rh
+gKL3j56IBOy8ARSNSHuKhRKM40UnXeYMrntpPc=
-----END CERTIFICATE REQUEST-----
`)

func forwarderCsrBytes() ([]byte, error) {
	return _forwarderCsr, nil
}

func forwarderCsr() (*asset, error) {
	bytes, err := forwarderCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.csr", size: 891, mode: os.FileMode(292), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEA1h4dZZxrw4Zx238gijTDaH5dmvgkmL87AXmetrjRCtBPTv+d
rG+a3uDKPbnNbxg4WE5c5PaJs7tYMWE93ToOJvBbMcbrxM7mVk9kUDEEeUqN5g4B
XysGIpiKjBFVmL6xrWionhv4+xMaQ3BRMJS6c7wg4WRhr6WninfNr79kJJtZJhvN
iix6fjtTOSS2ql9Sk5WhmPEMiU10VSFmDk4jvJI5Np9U4zlkddM1kEIsicbwoc1R
FchxFgZyf4hprU+np50naxx0IDRQnXul9/fXHODG0T8b4rHE6hgVouqfqBQTPee5
YhALfIBXEemun/5Sje8o+QWNAQetkTMH1B6bhQIDAQABAoIBAQCrS6BdAAy+ebpw
zX1s09VYrW+ZYNd2U9aS0YeFysmCCzDHlHvBze9qSw/A3fpZ3FiHXPm4OvvjDAf8
ST1C1QUpZbSvV+KaqqNffVhVR0G6/0gSOjYiurrHxp1gfSWrczOV9VqgUuSXiKrE
NQDfCr03hdQQPUxhRveIMVweM9Gb7i1++UC1dgE4fZkQKTf94TZNgUYYEXmlANeb
fuQOMn/cIWdU2cBJvAK1sfyLCfZP8abebpNxmaOnRDVhwZJdN3uLh4HzolxLnV/o
95L4Y+ruZLWA+JbGs4nooZ4hufu1fZP54lthffzghTbPGwrc9GXgixhGcREIVHCg
Wn7CzaSBAoGBAOwitdqXwU2Twe7WOadqCcI4X3sakrx/We0xIt5wb9+VkWKfTUO5
bhauT9l9tPj/HZoN3kwnqppGunzQZ/D4Eb9wGHrXsY/yq9WsI1o8yWxloqbe1yUZ
7q37RPDJlm4MHo3SwAVxdxJF2S/sVHnfjVgqcYJKqXhtQO2GYBxo14IxAoGBAOgh
PNaVsVOnIMN2qZdxqcUigYMNpgL6TgLY2NjmCCZV4/vuyLOLfFuvzKDYXekhNwA7
Vbt706etcNSoXVGzfBvmc1VTgGAj1nMUdrwhkTT8KyuvvL0afLeVK8LgOQJ5ZJ1v
L8NPsjSaq3P1u6wQvu5kYm5RRPLeunhrQHPiWuWVAoGBAKtR05awm3JpTT629kVc
TZA3zi5GbUeNLfVEvQOdl80jesOOyEPmeNTDyvMEnRQ6I4Pto+aksMYVop+DpKXT
lSzLazdU3mKNsdXoeg2yJIEcjBF9g6JLWjuoHbCE0TsuV8yVpvNMCxOa0aRPVkrF
worA4HGjMalJut2ZrIlwF0tBAoGBANE1s5lKzMkyJatE9VBS1smfcc5lrKueYFTc
j4PcvpeebZ2P9j8rhec0qF6G4wzMLL/+uiQBVB8ZiEmBfKm39DFJH8VVPqxnYE3T
sbeZIT/5zgbPmnFsv97NiOVYJMmAExh5Lzj+SQR0KfaXEI/hf9NnkfcPM+8YokMJ
lstaxMWJAoGBAJOF16jOV5aoqC9+ojF7tWcT6UY4CoXbNSFMUMVWBdInetFP5LIn
KCZcqo2c2CHsSUlD0wLuY0SW5p5Dud2QyEnTHsQ36yLRrMqX5J9y8+Jyp0YMQZ2D
WRZTezwGuiRSuiIzP3AH6aJYpThde21U9kUEP6Tw55skdb4NVSaz/vsR
-----END RSA PRIVATE KEY-----
`)

func forwarderKeyBytes() ([]byte, error) {
	return _forwarderKey, nil
}

func forwarderKey() (*asset, error) {
	bytes, err := forwarderKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1539359899, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrl = []byte(`-----BEGIN X509 CRL-----
MIIChzBxAgEBMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMTDWxvZ2dyZWdhdG9y
Q0EXDTE4MTAxMjE1NTgxNloXDTQzMTAxMjE1NTgxNVowAKAjMCEwHwYDVR0jBBgw
FoAUeCvnA8SAMl6jPOfBjQFPL4e4bOkwDQYJKoZIhvcNAQELBQADggIBAGYgGLIA
fT7CGOPzeidw/wPwyRg/A2KnpxO+o5L6DHwHhHa6CaRXozrTVmjMYyLIm6/kHBXz
eRmQLJMtcas9TbPVgXzbeud1j3Eek/SSifbdrOWjXRPOkUzX6PBOS0tT8lAsDYn/
n1uLFeoBushrYd32I8F1DCfjdD9SWEdIVxMtZkG5fwMGeHxI4Arj/ZyQpUxbLrl4
wTO/sqwk/sZ4/9TLM/qBw74XsEqWzrIbwuttGELmievht8yNkRnPFbw22BxEK0t/
9nywNzUZXo4PNGdPeUZWfjr15mn9+55toA6h94tfUDmarquRsFtIwc5QGRLazww6
NrBv66Ny7exp28pM7A/VCwfOz+GJvmkOeaD6jbSp4ecEmTN/jSlEIvPvj+nD7c5O
S3HJf2vyHc81YMPWmGuhpsQoegDtxY1tGDWBmILkMqOTOPY8/3yaCRfnPqrrs0wm
S6YeTSvbTjxW912BcFiTNzx6uqpnyMUTe1tpWxY5GJltKQunhRu4cXrO/YOoC9dq
VGmI1HFhMv8VveUCC+4HqeMxWAlcFATOdOf1u2cmCralSxY3TLIu0gkpEbbiXO5L
Mu01TrVbldAI2OAQfBEHOQw5XP0ec7HO1X4AKxSfS/Csb5m+V3b4PhZVElMU/qRm
a9VV150TfTIkL5aPrITwqAeFBYe4sLy4rzsO
-----END X509 CRL-----
`)

func loggregatorCaCrlBytes() ([]byte, error) {
	return _loggregatorCaCrl, nil
}

func loggregatorCaCrl() (*asset, error) {
	bytes, err := loggregatorCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crl", size: 930, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8DCCAtigAwIBAgIBATANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDEw1sb2dn
cmVnYXRvckNBMB4XDTE4MTAxMjE1NTgxNVoXDTQzMTAxMjE1NTgxNVowGDEWMBQG
A1UEAxMNbG9nZ3JlZ2F0b3JDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
ggIBAKYIkEbIJXBCzT+R9EvZfZCvRAWaREEqb97m96l0fZ7VNd8oVFxbHjMUUFrZ
Bry48rBgvnU2bZD4VNxTzJ1IlcwVWUCdmXZjnZcT6A7WkigStHVy2U08WKpM+9le
DhpnrrtJfhQgbCUB/soYe2YO/kOebyAbgAiDkQGce/6r1JZUwcfMJ9d0w29tlFWD
Lg0+9FWI8ZvfCBc83nqM8Q9kGH7gXs15orhsK9knWk1xZ2D7KVy7TAdD8QUDUN9B
5b3RzT+A96+3QIQGXLb/IJT06HBagN+KMd43qkpI2Htmmh1vyTxPlpEl0sNHtJxH
fd0XDvlcZnVvJxggy4w3mYm6SdvodNYNwGhzDBMr1Sr0M3rtP5tAsnenzR41YENx
pCppCT86hL56KSW3oM4f5wUiftZggpYKb6g8GPV2BoxGy3+DyCS/Ff5YUyN6Tz8J
fOkiyt01Nd7tHvjsBBnccBea4JvS+hBDpYw4sJKYhUu7fh0wXLP814j3pSxgMepK
0RSGRRAlY0s4tzpXNIgRqpTN4J/+HbT8AxhbwRlHr11nErfgs92jpqKvaLLxyQL1
b4IIr0dN54KDIVKnQaR0JVZDqbyil8kPUPbgRGGw1iRT0WN57+bEeZhzS0BtD+MD
aQDO89SMKcBweHR9IAZl2vfRCtjYafmJZrRS317eHNw5AkiHAgMBAAGjRTBDMA4G
A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBR4K+cD
xIAyXqM858GNAU8vh7hs6TANBgkqhkiG9w0BAQsFAAOCAgEAW7PKKjQnGHsyXTcU
+BjVcA0g6fuZn2rYSrKzSKfApH7BUbfFcXdDzbxjmuEf9lOcWXjxeuJiVQpIY4II
ZN3TouJ6aEgE5nzn/UWwXOvvySftLjdjMBbd603t77+BjES8EhDNsfLqvRLg6o3k
H7q3jculbCdvZR8E1sj0ID5pX2BypFlUsLU/porgHF1YJd8L/yJLTfjSiWLvyXmd
mdxz6CGgiBuomWm6VPxOPdg6XrfyG80KqDB6Ix7zHUNmKjs4anZGXKTwdJsTpTjg
K5sBHkHwA4/Jkasm96Q5GX73ZmsOuU9FQBjABOyyaQ7hw2rczO8ohEEAgZDJ6fKP
9bfu+plQpgeGvh03Se/XjKdty/BvnczLFb2/LkK4MZZWBCOipTyFoz64S+/s1wJU
eSlDkb3qj7QdnL6mUcUpn4tqns1+GDkuFe3Or4BFEqaBuKP/cWqcb6UWtyRgpViS
DNZlWtS+44X4b6FL1RYPMkVdMmy1vuT5xjO2ZmhdeWkRk2sbFEHj8j3ILDWumfha
WGTEFlCc81C9ttGDfOC0upSCp6e6d9IU9niBMj1jAjUT6hsKqrtOqqPq/i1rrZsq
hD/Le+keOAzHFzGWj/SfwxGKwasP/HGOwpQdFHWRZdy9EcAn4aL4brFmvMMZ93RP
vyOGonLdP/ziXYwG4lgVdjGx64E=
-----END CERTIFICATE-----
`)

func loggregatorCaCrtBytes() ([]byte, error) {
	return _loggregatorCaCrt, nil
}

func loggregatorCaCrt() (*asset, error) {
	bytes, err := loggregatorCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crt", size: 1773, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEApgiQRsglcELNP5H0S9l9kK9EBZpEQSpv3ub3qXR9ntU13yhU
XFseMxRQWtkGvLjysGC+dTZtkPhU3FPMnUiVzBVZQJ2ZdmOdlxPoDtaSKBK0dXLZ
TTxYqkz72V4OGmeuu0l+FCBsJQH+yhh7Zg7+Q55vIBuACIORAZx7/qvUllTBx8wn
13TDb22UVYMuDT70VYjxm98IFzzeeozxD2QYfuBezXmiuGwr2SdaTXFnYPspXLtM
B0PxBQNQ30HlvdHNP4D3r7dAhAZctv8glPTocFqA34ox3jeqSkjYe2aaHW/JPE+W
kSXSw0e0nEd93RcO+VxmdW8nGCDLjDeZibpJ2+h01g3AaHMMEyvVKvQzeu0/m0Cy
d6fNHjVgQ3GkKmkJPzqEvnopJbegzh/nBSJ+1mCClgpvqDwY9XYGjEbLf4PIJL8V
/lhTI3pPPwl86SLK3TU13u0e+OwEGdxwF5rgm9L6EEOljDiwkpiFS7t+HTBcs/zX
iPelLGAx6krRFIZFECVjSzi3Olc0iBGqlM3gn/4dtPwDGFvBGUevXWcSt+Cz3aOm
oq9osvHJAvVvggivR03ngoMhUqdBpHQlVkOpvKKXyQ9Q9uBEYbDWJFPRY3nv5sR5
mHNLQG0P4wNpAM7z1IwpwHB4dH0gBmXa99EK2Nhp+YlmtFLfXt4c3DkCSIcCAwEA
AQKCAgB9PNRnL61dwmXDX7qgRAt8yVdLypNVfEcqIZoKTf47gqPCEk+f4nMjIF2E
SVPVosQc2ryO+WEoCskn8GXU9d1YNXo/TSFmtbk3LiLKnntcks9gECNtKOnQe4U0
7sdAj5izWLorQFGSkLC5jEH4N7L/GlDELTokMel9B6ZX8RDH3GLW7F3ZHRAVytgq
sGpaP3RZ2JQ2eMNHk/hVBF8Itv3rJh8canWdGqrwf8iTxciu1ITcl8K/cDYrC9dC
sBg1WD2zevpZpqaZb5sbxdGzyhBSP1IaS8lVzzM6GTyByGDTd3CZd4chMSCLgFjx
0NNVo4D+Av6d8hvRDVu8BmxgAQ6YBPZYZnN5+3x3gsEoGKUsN3lquQKrBoL9aj0B
edObLtibzj/s4YbtIT11yJOsL/BPscmpmqcpjVvSuo7/Ieu6/p3veDasSS4RRZ0W
tarEbJNX4JRE2aPmVzgcftRLkbxe6CIU1RHwhq+SfAQTdpauLZkeWsVB8pA1XVjZ
FcimUBpwgJV0wMAjjPIk5AugUc9HkJoe/sW9ZIvty2A3vRjTqD4DKnZ/c/g2+UgV
jytH4VGNjm162KfK0OZ78z4b7A0rTcJ2M+hWdFAhXTXdB0NVEV1a5NN2uVN4qfAv
FoMDuSP0SjT7YD1PJEXegS2s0d7FivgW3IKHwLmBpZm5+Bo/wQKCAQEAz1HhCbiu
zL/qZxv+UEFSVln7sYK7Cw2RMaQDRPEn0BYoqFyQ33TB/5AWlLgheGk9HpudL8HT
jSA3BDkcaPprGGwfQImld4PcNyvnmLeXKAOTaDH1tmS80gIiTezgKH2Txw06ALd+
AHdgcWYaCXKNi7pBRW2etdCoCmZ5I4ap7RAtvGHxfgWh2Z5dYuEIUm+L+lRpWXbh
6bOlfVAS+E3rkyrJtOij8V/4ggjrA5FlwfUuzXuZ6s8ezhEKTieDZDD6mKFuWjEO
kid2L6WET0jyh2G/0jrVLys/xFingrVdRO84++JE5HD+OBHPX0X4Zxg6g8ay1sw2
kIXKOKk44XZQFwKCAQEAzQTvS18bZXLOrMDS7/Ym6IDrNNfoOxxE7qKuHMjxCiJ1
daUUpWzmgmlml124h0qzwDECQcgLPiSgiowgNEOgSsqdnEMuV3ss2loZQG+s+1Qf
racc8DYjegRZxQIfMKOtks1rHsInPU7uARj2NdxugkM0AQEDX9g5pr7tn6IEeN4L
0CnkZr5f/Hbjgb2wFT0OlpTGpLAW3WNfzfyh2fPzYA5RBwrAyGntFgfK2W43OQRS
UN21FnVrfolZVY05Xg1jQ+w0VP8KwqOotC7CcHlr5l97JlR0AiX6j8q1hzdEj/mf
ICp0ErYRTztBK55cVL+h/5ir1UMQe9d17mv3L0whEQKCAQARpgu9Mx6WSYQf0O8+
T8E9np1hiBp6H2aLzkWE+e6EtU4yvuaKTzswkUiK0n3u7S6Jy39/EEX9DpAAaQg1
G5RAWPv0F4Ohf/UgMTme84oHmv5ScWZUZ5D3Y70d2xtd9wq8eDDG3Nf6HC92l9WB
lmHcUje6PFG1cpTLhdusHYubpbPvBHt1We9kQin6/+MgeWR2I/dv6UHkDin5V/a1
cpSqS4suPluucZgLIc032YnLEB8y2OHKbmVV73dsHcr+nXjHw35MaT6vTHKwLavs
v+39fmHA+McrI8hi45Um+F9/PcohDysEM2ZAyatYlfFGfXaFv0V8KZg/h1QmrKkt
8E9zAoIBAQC4q3FAWvK6dqdjRGy8aOSzGSzD9JbiZ5xPt4lNtFIp5tAWoBPwzh7z
6SzXuzuz4b33qC14Q1CdMTDKm12GtkN0Gv3M+1aKxhCove9w8ybFXAkMyjJuzNU3
2yNhKYAet9BpI08R7aCawLXxlyJvcZa5Dv+Qx/DaLFIBuIkh+TY+CQRrBNEPGvwq
1IwpGUu6Vb0GNgyX22U9FX3+dUj0oaDfLQYfabgszf0YkvxMzdJAMXxUCuBK0ol4
+Q7W2NaLuVNooyKgTPrMR852Pog196kRYX/0Dq5QIRWI3/aTTV0csqR6vMLA9+6v
h5g0Sfiw/cxWBpcBCd+XLYS0tdt5ZwGBAoIBAQCWQu8um4ClXeKmTypUxZrmBTjm
rjxqB4x1CeZxmZNGwh7DQ0g+EutCPik57+xq5SFb4u/niiLipXnfOVeGyAz49UYV
Xw7dsX1VHtGHXFhxDTvfzoKvFyDruxWyJX9/MxpG5boR1boOpKGCID2seURdZ87Q
lTxnZ29meZKNb1bU9SvDaqLygEK8YYmkC/GYx+G5c2ZHaEBZU1nVmbfUKPDjHKX+
YBrcr3ERMsoUb88GMpq2uKtAUdjHSh3qfmdHC/34A7QenL2bpIbNpVmjdLSKgsfI
/Q8zgzG9Z4CbYwj9a/KpfJH6QC8VyaEfVN4P9H0lmD59e/5E5AF+TL64dl6M
-----END RSA PRIVATE KEY-----
`)

func loggregatorCaKeyBytes() ([]byte, error) {
	return _loggregatorCaKey, nil
}

func loggregatorCaKey() (*asset, error) {
	bytes, err := loggregatorCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJTCCAg2gAwIBAgIRAOs3zvXtU0LzsJ9UfR5PxyEwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xODEwMTIxNTU4MTZaFw00MzEw
MTIxNTU4MTRaMBExDzANBgNVBAMTBm1ldHJvbjCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAKn5uWORSgYQL2d5XpmUiNmajpiKrtRCLiC+AC8RmUfg8GQx
3Yp/UbtzXcPZqovW8aCaHtlPWoeQd7w1wZY3Dc8J5InrJ6mfJddxU3F3KF+V9hFz
/7VpmnxxzzJDiq4sVvIHLhRlu09qOHA9Rlm7ypw2V8eiOk3/LOEIttriXtBxX1P8
1QjmJlGrMKxUfIuLhEBGxckflwfujpLS1nmVyNpweUYlh25qyK9UkFCY1qaWgOcu
zwdP1ZcYZdtSzOBjySxFbeeusFGOXhYswx+NFrsJiAyKF5DxQKdDOFQSVjwoaZZS
zspIv2460zMQK79yETHZnps0hSjo0Ld1zRWHgJ8CAwEAAaNxMG8wDgYDVR0PAQH/
BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQU
NMkIX1qCPNx6q17veh5SNBlmwoswHwYDVR0jBBgwFoAUeCvnA8SAMl6jPOfBjQFP
L4e4bOkwDQYJKoZIhvcNAQELBQADggIBAF5voA6hxrZzAhrTAxbQONG16luMIseb
+2/afO/40pTEfGZt15CeELmjyNR3nzPCQ1eV0UJmVwYbhB1sh86vqb19kx4CYQhv
2o1HUe2Snp3Dnj22WUhM3nBvineCHkrb1q9AeZHdKMtZuH50xu8lNfeVr9Ek0Ysk
HNU05ANLgLL35fs5YZrJW+8NMVODB/HjTqvF9+DwJcqTqcHUcycd4PtA75szRjeb
zy2AfXCeo3ts4zZOw9VdzgNLosmr6Vt1vgVcIZLK7wPo7HmMFaEjfbx/VlTQr/D9
Ke0OkrAItMQ4CQgj+hIPYhvVvPTH3+XmfZTybxvcN/ECq6IP6pE/PEXPglNGLsXs
qFPK6Vs5bzOZVLagIMLCyYFMArGLJqNqxt6yZgAL2TLEqnVKecqjPgRqd7m78nsI
wb94C0mi0rxmk6ivSXftwnDZq2M9c/Bxd+EPAZ+nSDDa3XvZm0SXZlyI2xhEljTC
TB768eFC9myQL+uyM4j4Aov86wOJAVJ+oogQEBS2cYac2l+Dey46BBLK7l1zk5cn
bUh45aUAEpI/ltYtWUI5PaJaj4mmL4beQ/n4yxDys6Adg9V5plltgtqxVVav/z54
SUvoSTSD7UbrISwsMdTM3sUIb1qfFJ3/XpNjl1bE8ISTYLuPI8+XOHBLKHV1CEeQ
e1olbWaD7Lah
-----END CERTIFICATE-----
`)

func metronCrtBytes() ([]byte, error) {
	return _metronCrt, nil
}

func metronCrt() (*asset, error) {
	bytes, err := metronCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGbWV0cm9uMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAqfm5Y5FKBhAvZ3lemZSI2ZqOmIqu1EIuIL4ALxGZR+Dw
ZDHdin9Ru3Ndw9mqi9bxoJoe2U9ah5B3vDXBljcNzwnkiesnqZ8l13FTcXcoX5X2
EXP/tWmafHHPMkOKrixW8gcuFGW7T2o4cD1GWbvKnDZXx6I6Tf8s4Qi22uJe0HFf
U/zVCOYmUaswrFR8i4uEQEbFyR+XB+6OktLWeZXI2nB5RiWHbmrIr1SQUJjWppaA
5y7PB0/Vlxhl21LM4GPJLEVt566wUY5eFizDH40WuwmIDIoXkPFAp0M4VBJWPChp
llLOyki/bjrTMxArv3IRMdmemzSFKOjQt3XNFYeAnwIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAIOsOPIuEvAL92R+/sB1meBbQAkxCVzxSCCfw+GcN+Sw3x805t01
sUWOsxtnhw8oe4QVxQnjD9IBtRY0sA4kKr/1qkGjnVqz9pXBJ/aw937PHapP1Jd8
Vk6atqt4rWAASXhmXchkPY8oFsHYrOCJAXFKGty9CaTVC0zcXq4GXV77EoqP+Uw0
YVeiwnoGmgRgGL6OklqOHvBsgKZX4WnApvWNNsofDkQQuAG6FrN7fUChAR3tUCPs
yTdPLKP2Ahvm6hIg026G3ZPRfO+6v7MJIkYCKmU071hA3j75yWHb+O2H1VpFEu9x
8VhrUWiCyr1VZi+aaNXvNZbkPcXrWNEzBi8=
-----END CERTIFICATE REQUEST-----
`)

func metronCsrBytes() ([]byte, error) {
	return _metronCsr, nil
}

func metronCsr() (*asset, error) {
	bytes, err := metronCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAqfm5Y5FKBhAvZ3lemZSI2ZqOmIqu1EIuIL4ALxGZR+DwZDHd
in9Ru3Ndw9mqi9bxoJoe2U9ah5B3vDXBljcNzwnkiesnqZ8l13FTcXcoX5X2EXP/
tWmafHHPMkOKrixW8gcuFGW7T2o4cD1GWbvKnDZXx6I6Tf8s4Qi22uJe0HFfU/zV
COYmUaswrFR8i4uEQEbFyR+XB+6OktLWeZXI2nB5RiWHbmrIr1SQUJjWppaA5y7P
B0/Vlxhl21LM4GPJLEVt566wUY5eFizDH40WuwmIDIoXkPFAp0M4VBJWPChpllLO
yki/bjrTMxArv3IRMdmemzSFKOjQt3XNFYeAnwIDAQABAoIBAHOb3aNCK6XqFkP7
wgMViurue7R3ByhphvRQJtHc13OTJA4R+Iv9wvqLIihWgPAyFxBUI01M8tcnxLin
m27vLR43rVC9N7HgBB3//3A6SqSQ29fNHQwnsqKXygR2+fkzQUPG7GmFNBx0s8Rr
eNEJsGoFcDjhN2TbfYvloHFJ7JE6nr7qmhUQSpwrLCJKszzVH/BbRqEkGS0kUbEj
/k+Z87PbH0QRY63iVSJmxYpPpTSNTn3549RzoTLdnXkaINWMPh7gkkCEzAUaL3y0
u1R+yfbN5ICPvl+4gENQuOqYrXdk/JUQIVyFebSeVcsCYgTqLCh6Mwq7FlQQ6P8h
pTbhu6kCgYEAwaY02KHWe2hjMSPKNubGAB6GziwNAoxN6ODaCn+E7Wqru+HcqG8z
rf8MFnyXOoRA4bolkjcGzDjqXjOHnr62tz3kD1hnVMRxJvFhJ7yl8ob9aQgLsssk
ySmpAXke671zBhjB6eE87TDu4yCL9EHg2gBqVGNSdWYDNK0/3qcHVYsCgYEA4LQt
Us9U0Rg9AoRiD7T0H3mYddhcR58JbQT0xiTlh32JKmanHga1wGtsbCc9is/MCIsi
k82GpSivAdViim5l6KkNEit39uFnpJpIAjotfIMS2bCLhF5iBJg6RiLLQnn2Takb
Nwt6KC3Y7eNRhCjZaAR4Pwf0tYwfkZ8hz6sdK70CgYEApysSzbwPyqLXljEePHzF
io7PsqWGaZ+zFgkdURi6KLYAIIYfFWxBwb+9sJ/HcSWAWRx3mJxWCvBLKhzzw49B
bjhIaxLWyO93+rU/OK162D29/vCKIMOLMvj6w6HKlpkJ9cZjh8H/9YZbgsiy6J4C
PE9Feynuohf5Rn0U+OFZzHcCgYEAllRUgjNNVjo2DuoMRN/V9vy9oBGo4w2mG7aW
H73thXDaBHD62x64F8yGk/DIvoZ4xTp4XpPAwdvvAXYF4AEt0rLOmNpV/ugcE8ZX
6I2NguCaCuOO43bVcqd5TRTYEVhRDPHW0EOwbRMHL1fGYHmHwYxD+j9TWuYs9JqW
3z1mXa0CgYBpJ+iJdSB80YdqxwTrwvyATtCUlmxoKtWaaq3BKm6CwR67xISEiXeq
4wJaXKq039GVN1RXmUqZJIwhwEBm1dqzD8im+lDoi9Yztg6rt/vnXZyrp5vEz/rh
gUxoH27MsLXCmHcVERGU8umdgpRT7xnYKk56KpL1OuRPW2Tr3ckdVw==
-----END RSA PRIVATE KEY-----
`)

func metronKeyBytes() ([]byte, error) {
	return _metronKey, nil
}

func metronKey() (*asset, error) {
	bytes, err := metronKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEKjCCAhKgAwIBAgIQROHLkXhb8H1cSg0jP+Qo0zANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE4MTAxMjE1NTgxN1oXDTQzMTAx
MjE1NTgxNFowFzEVMBMGA1UEAxMMcHJvbS1zY3JhcGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA8JX3MP+crlD08s01Q36dxlKE7Kr4Nli53Crlu84B
bX7u2OLsEUdHdubHU8baDih5mkqDj+DU/qdQd0gb20hmSZOdFYag/qI2JDVZxc5Z
9DC+wqlvFBkZLx3R0O5qQDqqLMaB9fdlYTXWMTUFXa+t5ILKe8zNsqwgmdsrE3Ff
o72NhAFq6pHxbP9QZTP+lxOHL0H2uQB3X4QDufAQ/8t+DD81Wazvt3H6ZWOebJih
Dv3NXmVQI1g+ufmapHjwypVbSds0W1yAHWYLpEw4laxNl3iu7ASoPUtOQ7bM4Ont
dIQKeh4bfh01wfRTM8nSnrYHU+oReLQ0Za0SX31F0OPxLwIDAQABo3EwbzAOBgNV
HQ8BAf8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1Ud
DgQWBBTeIJNpqYl0EC2AMjwDo3T9NGieHjAfBgNVHSMEGDAWgBR4K+cDxIAyXqM8
58GNAU8vh7hs6TANBgkqhkiG9w0BAQsFAAOCAgEAc+qSo8p6KKn5K/xOhCL1YIBU
px16KwEdMX+XN51lGewpBZerDaLSGH1B/itepugt10lOtHnxxyNHroxeu+AwbTYU
1LeQyWdJAohdpi7kRWKb+s6qbtpwgX/kEzjtJGn/rg7xDTX53+LRn6rEcIgKCGj2
GFQGzx+yP23Zb2sAHyvezw1BM5Cp+ojMUViWZAEhe/fvCagQ6ijO2ss0JnBwh+tm
NtoHytIhTh6S+Q97BL9CcmMdWVqQxJsC6v+MzYUSrQhpB5tRaF5gZmea7PPywkvF
Cl8PWIoOVtHNnP+B/lBTgAztz5+h9j+9ORGgyaBJXLUhzjrG2Nja/0oC98WezWrL
11GvokYQ/ilc8DK329Y5AaTy4xSg4lZlyFK+f78aF7lqCA3+Gh4dlBGoGkj+kmRk
FVb7S7AAeN7hVDs7QBftpKbYOVUzPsBAFEiBingB8GaYNg318mzqgsVZKI7eKaI7
+/Sh9c/Lfngb3ufrmmozbAZD4PD6Tu1OSMIPo908ERHp1Cr+ayQDjd/gdeJRXFW5
+4DlJtnvjMvKa3NzWq9/RQr80wYtu20qZJUy35uS9nPDoJXUw0tOrc3ksFNDB9DU
6zgbh/dF9dmvhC80u7G11un7uze+NYhQKZlg9B3LbHoTL86O+wG9XNCwuBkSoWL9
RvIu06MVKUzuQC2LdLg=
-----END CERTIFICATE-----
`)

func promScraperCrtBytes() ([]byte, error) {
	return _promScraperCrt, nil
}

func promScraperCrt() (*asset, error) {
	bytes, err := promScraperCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.crt", size: 1505, mode: os.FileMode(292), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAxMMcHJvbS1zY3JhcGVyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8JX3MP+crlD08s01Q36dxlKE7Kr4Nli53Crl
u84BbX7u2OLsEUdHdubHU8baDih5mkqDj+DU/qdQd0gb20hmSZOdFYag/qI2JDVZ
xc5Z9DC+wqlvFBkZLx3R0O5qQDqqLMaB9fdlYTXWMTUFXa+t5ILKe8zNsqwgmdsr
E3Ffo72NhAFq6pHxbP9QZTP+lxOHL0H2uQB3X4QDufAQ/8t+DD81Wazvt3H6ZWOe
bJihDv3NXmVQI1g+ufmapHjwypVbSds0W1yAHWYLpEw4laxNl3iu7ASoPUtOQ7bM
4OntdIQKeh4bfh01wfRTM8nSnrYHU+oReLQ0Za0SX31F0OPxLwIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBAN3rZgzU9/Mkb31uVdWkAsA/el2CBMgRHAnL7u/lXkAe
NtLbh9jdVwpGxI7KDib2Ep5fbDuH6+ByNXRiS1IlbMpQdynkXitNKFAYexUM6Z+G
g+frmVMANBegwBBno9RmVC9qwixVLugAQHJrXnsW5G4bnX6BO63+cy5L/1nVE4Ym
ieaAtaDygAZ7H0ZSfJc8Z3Ob+Gzf7f7azWD4pBsdMeWOsMqk5R46wl8yPScIDaof
uDYI66hYsUWtLv4cV3TYysc4V0Y0v33N/2UT6QdYgQgrcMIC4xARjeaBN2TfihAa
OZl3R0gn1BBN9hbXO+JbGYVPzglzR9bpKR5TgskxVno=
-----END CERTIFICATE REQUEST-----
`)

func promScraperCsrBytes() ([]byte, error) {
	return _promScraperCsr, nil
}

func promScraperCsr() (*asset, error) {
	bytes, err := promScraperCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA8JX3MP+crlD08s01Q36dxlKE7Kr4Nli53Crlu84BbX7u2OLs
EUdHdubHU8baDih5mkqDj+DU/qdQd0gb20hmSZOdFYag/qI2JDVZxc5Z9DC+wqlv
FBkZLx3R0O5qQDqqLMaB9fdlYTXWMTUFXa+t5ILKe8zNsqwgmdsrE3Ffo72NhAFq
6pHxbP9QZTP+lxOHL0H2uQB3X4QDufAQ/8t+DD81Wazvt3H6ZWOebJihDv3NXmVQ
I1g+ufmapHjwypVbSds0W1yAHWYLpEw4laxNl3iu7ASoPUtOQ7bM4OntdIQKeh4b
fh01wfRTM8nSnrYHU+oReLQ0Za0SX31F0OPxLwIDAQABAoIBAC2ekifVYFVhfoEH
zmDFAo/Xl+L0rGpJurx32eYZswWbOxkfNlo0ZOWz7voAy9pBbIWIOZgvrtO20Dg+
ESIsgVDUT8YEKEUAZznIcARlE4ONNq7cx/ZMqAzaH635d2ZEeX5SCdSlG7EqLzpX
bnQMWvHopxKAjESkBO6Hs4xVRChc6/lm/UW4xZBBdfHW6b8CBg9kr7a+s3uCPHNL
JY0MnpjrfbfnzZdM1HXgL9nTHX99Sa0hczqIEGWB1u4jdAeCxFXdBhgiI2yfovBF
n1ZIX75giUWZtG5RTDzO9yw3IOEwglBxgQnrV6rH+6JO06k7pCGRoXo/q4PsyNCQ
xoUZUdECgYEA+P8pM76Ju/esB43J43rft3zKNVBHf00Mn5W7T/7CDN+sUsDvsSDx
3YwXu6V8nZ3WG8JQbkqkSXtNxgUzHoK+3Z5bBowEesbWb7iZPKl1Ef3ho7ZJM6Fn
fpn9MYNHyJV1T1SGqb42sWYyuy+ExYNXL5O9cosyc63+S07XBPFroZcCgYEA91o+
cOEg4dIL+5WJogXwLdpAkKjs1f6yJOM4bInsIpfrjmpl/fEnWdTvuchttSX9K90n
w+olOE7BVAkWrzg6Hf0292F0/nZoZSV4sXmkjt8cO2QlLPXrN0J+IlsX5LclkP/l
kkTOR2uQWbxoB/noy6dq6klB8BtHbmTkfDRTcCkCgYBO8j/zCweKlGVz463ONUg3
WhaWvsRchWZqNsQ0Adcu08BEYK3eoE5vaxqfQUH4i3G2TW7I+VuLfM/U6BMkKlov
1CSSN9S3xNF6jLHxPN1EfhWLnaEqAJPa3SIdD72zyEdwhqFHsmqO5pNRLCjRouoC
yLn5Vk8BxHnrEK02AQGaMwKBgQCR55ehegqtaftLgd/XxOzx/yXKrvpVGJH4lFd6
Hrk9hqOaNETJUHDH2oU173ZXPntiXmfQdtNRrZL4gQvye5Y8jlrX/ZLHbw0RbNMO
zRQ2eoDqv532MXF3/S7uERG9BhOQvoGqkA+lrVtOs4Yh/lZFmxHD9UaB3XV7NuRY
J314UQKBgAhLgpGbLZAOhM0jbHW6NCeCzMKApDjdqUolC5nxCPAqfjncwrMxSVGP
az/y2VUpvfii8V5DBJ0x+ehgV+q3EiwKheLf7PG0WrKmBFsoEASLBmAb5wZM9uEB
Gb6rF3Br5SzeaccEqFaimJCnVK3XU2qMVYVpK/6N/DSccPDIMA/O
-----END RSA PRIVATE KEY-----
`)

func promScraperKeyBytes() ([]byte, error) {
	return _promScraperKey, nil
}

func promScraperKey() (*asset, error) {
	bytes, err := promScraperKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1539359897, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJTCCAg2gAwIBAgIRAJ54f7VFGRuSXMF9/inTs/AwDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xODEwMTIxNTU4MTZaFw00MzEw
MTIxNTU4MTRaMBExDzANBgNVBAMTBnJvdXRlcjCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBANi7KeWEn7I2JqxveDU7N9CmCl3wmw3YgAIg/uIaorTedvXt
jArmn9cs/FhCevy9x0W+zgnQg8U7pXvXBRY1SH2PrAp7vxV/qc3Th7eYeAznqXyE
CGlKGG+Ww88CO6F6D+fRrigvuX5DdXhGbjpThomw1qrO5yIGSX4aqtVsn/JUhEBA
zzy6sOEuAVueHOrHX8Uml/HcoBXbS21vmPP/gjh+nsj6I53L001zHWRR4ao+x1Ft
yzQ/T/o5mckudcE+gOaACQKno/rGpjfI8raR0g+ofzmibeRI1seR9SlSkCYZ8ojV
DYFGcUqMC3u1Y94hlDcrAy0X6aj6UfqkfeTdOb8CAwEAAaNxMG8wDgYDVR0PAQH/
BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQU
5S1J56zw86bBWGPMqez/kDcdFeowHwYDVR0jBBgwFoAUeCvnA8SAMl6jPOfBjQFP
L4e4bOkwDQYJKoZIhvcNAQELBQADggIBAHVzYNgwNKEmCVitxj/eibe6bSsfBByI
pE/PePapxP/dT4+btl5Eikpnwle1p8/DwVUodQmBEI3aHfUTWF6GlmtQVRRnsknj
KEhxTwWeMKcuViVRLOUJjl+NP5sQewb/KAMyuk8De2+HmmQ7oxZTwP/GXW6fZSTY
tHWWc8nnF1VrsP9xANhDnxiIT7HLhFRjSJBoCLJyxDBt6m/qwJHg8bmkrXXZOJfA
CoFu8wn0t5yNuYNX+gVfSyxiz4C/nD3AWPUUINRNL6i8S5ngEcxZYIrZApPw0zZe
F8V/UKArEi8S+9QKqOQc100N33Gk7wnNVslGTV3heHEiHkRGjEOaf3jnsTHkiUE+
Vw9KPAdwvVCdET7U0qbvvvWwIfzDtKx/npw/1JELPPvoohikTONHrwnTXoyQBdXt
YFQmDhbGlpTOLJ16XhdKSp2NrZtL3Vs68ezBwnYuDRdO9IuxpeZDFnZlMbdczKO9
PDBjB7d4RJq3qIZymmy41ZL2MXXFNhPgHnVUydHCQ85115V08AOLZkOZUofywgjH
pqhB3XoTdB4ilzh7wdPIty4WnqOvvKsq4HZxbW9q0xERQtlwB8fjjxPM2MAzoysa
lLaj/mlRuvxUxnIMpZF7QrvHIjUZID+xFp3Hrqv1xWpyT2a16eLYkDTlBv4XKPtq
NFn2ffXaK+59
-----END CERTIFICATE-----
`)

func routerCrtBytes() ([]byte, error) {
	return _routerCrt, nil
}

func routerCrt() (*asset, error) {
	bytes, err := routerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGcm91dGVyMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA2Lsp5YSfsjYmrG94NTs30KYKXfCbDdiAAiD+4hqitN52
9e2MCuaf1yz8WEJ6/L3HRb7OCdCDxTule9cFFjVIfY+sCnu/FX+pzdOHt5h4DOep
fIQIaUoYb5bDzwI7oXoP59GuKC+5fkN1eEZuOlOGibDWqs7nIgZJfhqq1Wyf8lSE
QEDPPLqw4S4BW54c6sdfxSaX8dygFdtLbW+Y8/+COH6eyPojncvTTXMdZFHhqj7H
UW3LND9P+jmZyS51wT6A5oAJAqej+samN8jytpHSD6h/OaJt5EjWx5H1KVKQJhny
iNUNgUZxSowLe7Vj3iGUNysDLRfpqPpR+qR95N05vwIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAHWgd8n5oEmHgoXxI0+emAf8oaaGhDRWMuR/tx/11/7JPUQklU4s
OatjfgNboiUY4VlBxMX4vfTEFYRwjZoWPTTzFOXchEIwXvwJYvBdpJol6NYaVlsv
8z9JKnYIVP61YqiYUAekeRW+O7333GaaOLnCYRMlWh2405t/F9gM9hEUTaBUkCx0
CUR/fsKUjPTdTRw4iZ00aOx97Uh3y8ICTmDA4zizzECW2NuaMzP7ER1f8lrI4KYf
pES4Qhoq5iMnp0RZmP4NxZ748dxs9581UD4u/n2n/ED0fC/rFsBV5oO1j+ZfcyHM
BR+RkMK9cJetQ49l/tF0EHSb3P5hTCmxXmY=
-----END CERTIFICATE REQUEST-----
`)

func routerCsrBytes() ([]byte, error) {
	return _routerCsr, nil
}

func routerCsr() (*asset, error) {
	bytes, err := routerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2Lsp5YSfsjYmrG94NTs30KYKXfCbDdiAAiD+4hqitN529e2M
Cuaf1yz8WEJ6/L3HRb7OCdCDxTule9cFFjVIfY+sCnu/FX+pzdOHt5h4DOepfIQI
aUoYb5bDzwI7oXoP59GuKC+5fkN1eEZuOlOGibDWqs7nIgZJfhqq1Wyf8lSEQEDP
PLqw4S4BW54c6sdfxSaX8dygFdtLbW+Y8/+COH6eyPojncvTTXMdZFHhqj7HUW3L
ND9P+jmZyS51wT6A5oAJAqej+samN8jytpHSD6h/OaJt5EjWx5H1KVKQJhnyiNUN
gUZxSowLe7Vj3iGUNysDLRfpqPpR+qR95N05vwIDAQABAoIBAQCZzViSFGfv5BXV
0NURkZCudOZue8zNKpLM7/VxJ03H5QeuxoDXS4qq/LWnPKZirZq4mAtHU73vPcDV
/WUSuYVT9Z01Y1PbQdmSw0ZQt9aZ8dyJDHmbnoVwyyDxyrfeg+y9qkNZKWUNgXnf
fLvEkHmtRN1SIbpMnwGQiAQrqQZoxNqK5NULjMi5JvXyin1LAC9TJHEm3vDxEeyI
HBZzByPPfMkdAWKyU99CalBJa259aCKb1ZIRgKl5Z9/jHlh86YqOpdXttHJfk6eI
3ARh8yuqwdj3AvDnKSL3OzBv9WaHp+FAlq+Asr9xAWnGwA7KgfpthCGPHexKxVQ7
gEzCc8JhAoGBAN0v3IlAVU5+f6KYezKmGS0A9vVlXG4+BvKEeI0/LJ+77d55V8qf
GeRLVImVb+gPACptTkFI9z4j5ZUV2yBzYc+YFdO8LXl55MSKAEkI2P5TH8XD/wqQ
GTT1cDkUxA83A1PHZ3/N6W9UU2mge0dtFn8HLynnGgu/djS0lGfXffXzAoGBAPrX
w/wXpNZ/CqxjcepkZl0cMTJUC/x42e5VREq0MtKCX/Tmy0e8Dig4QJoVq9V+JQzZ
8zTkSXC+hQXOkjfN8zKX4sYh5Ih/OEiyaPeLYHYKW75opfbsjziphO0j9X0kHaOH
5V+ZU3OCLuKWaVpGdPBVIrcP3/33VZMKuN9d+eQFAoGAMnaA8i9jRw1FQWtYcC3F
AKd/sGz3sY8lNp9SgacwHyFZG7DDfs7dsWAeYWVeqqsBdqyJdguXnO3Dq0fZPoYU
grBICo6cMWLF9rElb4Q9PYjpbs1QmrBVj+ePOvap5G7Aq5SK4HWyFFxAy5B5j8or
n7+b2wuGvbdo2I16blaTvlECgYBPX+tSYCD3BuhXuHgZlX+Www8GP/YzBALiGfUs
Nm1Gk57NniKBJo7MR1CZ8XWYbvxGXslI2Vwr4v2w4rb+FZt5TPqje6IXVzp2No5k
lqQFdi2lyPOLeTuw0GORrqlF2iHO13fLkncHvBAd/z6DJHxoeGgtyUY11QgtKV1q
wRAMCQKBgQCLY/pMTd3tRh/iwFryNFd2GX4th5Rcopl/woFJlG7+FGH3o58WUd38
sU1QuSRvrfrXze2omFTg81YPu22VbvjyRQ3Q4m1NZUjT9ZmSosjGT4drq8lcCY+8
FMsxVcKl/sOmVUB54b1JYkjctzveTu2uL9rtNO5r3lH2KxcScTGGVQ==
-----END RSA PRIVATE KEY-----
`)

func routerKeyBytes() ([]byte, error) {
	return _routerKey, nil
}

func routerKey() (*asset, error) {
	bytes, err := routerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1539359896, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"capi-ca.crl": capiCaCrl,
	"capi-ca.crt": capiCaCrt,
	"capi-ca.key": capiCaKey,
	"doppler.crt": dopplerCrt,
	"doppler.csr": dopplerCsr,
	"doppler.key": dopplerKey,
	"forwarder.crt": forwarderCrt,
	"forwarder.csr": forwarderCsr,
	"forwarder.key": forwarderKey,
	"loggregator-ca.crl": loggregatorCaCrl,
	"loggregator-ca.crt": loggregatorCaCrt,
	"loggregator-ca.key": loggregatorCaKey,
	"metron.crt": metronCrt,
	"metron.csr": metronCsr,
	"metron.key": metronKey,
	"prom-scraper.crt": promScraperCrt,
	"prom-scraper.csr": promScraperCsr,
	"prom-scraper.key": promScraperKey,
	"router.crt": routerCrt,
	"router.csr": routerCsr,
	"router.key": routerKey,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"capi-ca.crl": &bintree{capiCaCrl, map[string]*bintree{}},
	"capi-ca.crt": &bintree{capiCaCrt, map[string]*bintree{}},
	"capi-ca.key": &bintree{capiCaKey, map[string]*bintree{}},
	"doppler.crt": &bintree{dopplerCrt, map[string]*bintree{}},
	"doppler.csr": &bintree{dopplerCsr, map[string]*bintree{}},
	"doppler.key": &bintree{dopplerKey, map[string]*bintree{}},
	"forwarder.crt": &bintree{forwarderCrt, map[string]*bintree{}},
	"forwarder.csr": &bintree{forwarderCsr, map[string]*bintree{}},
	"forwarder.key": &bintree{forwarderKey, map[string]*bintree{}},
	"loggregator-ca.crl": &bintree{loggregatorCaCrl, map[string]*bintree{}},
	"loggregator-ca.crt": &bintree{loggregatorCaCrt, map[string]*bintree{}},
	"loggregator-ca.key": &bintree{loggregatorCaKey, map[string]*bintree{}},
	"metron.crt": &bintree{metronCrt, map[string]*bintree{}},
	"metron.csr": &bintree{metronCsr, map[string]*bintree{}},
	"metron.key": &bintree{metronKey, map[string]*bintree{}},
	"prom-scraper.crt": &bintree{promScraperCrt, map[string]*bintree{}},
	"prom-scraper.csr": &bintree{promScraperCsr, map[string]*bintree{}},
	"prom-scraper.key": &bintree{promScraperKey, map[string]*bintree{}},
	"router.crt": &bintree{routerCrt, map[string]*bintree{}},
	"router.csr": &bintree{routerCsr, map[string]*bintree{}},
	"router.key": &bintree{routerKey, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

